### ISSUE TITLE
Mac support KISS mode solved using node-ax25

### ISSUE THREAD

**Issue by brianN0KZ** [la5nta/pat#109]
https://github.com/echicken/node-ax25/blob/master/examples/kisspat.js

Currently in test with Kenwood D74a with KISS-over-bluetooth.

**Comment by martinhpedersen** [comment]
Very nice @brianN0KZ, I like the approach!

It would be great if you could post this at [pat-users](https://groups.google.com/group/pat-users). Maybe someone could write a short tutorial?

Thanks!

**Comment by brianN0KZ** [comment]
I was asked by the node-ax25 developer to wait a bit while he did a revamp of the session code.  There may be issues with large queued data and the D74a.  

Nonetheless, the usage is in comments at the top of examples/kisspat.js. At this time it is an example only.  More to come.

Brian N0KZ

**Comment by martinhpedersen** [comment]
Thanks Brian, I appreciate it. Very exciting stuff :-)

**Comment by kitchen** [comment]
hey @brianN0KZ, any word on this? I'm trying to play around with it and not having much luck, sadly. I think newer versions of node aren't happy with this and I'm trying on ubuntu but can't figure out how to run the program (I have no idea what I'm doing with node, I'm a ruby person generally :)
