### ISSUE TITLE
Set ardop arq bandwidth per connection

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#120]
Users should be able to control the max/forced ardop arq bandwidth on a per session/connection basis.

These properties should be set using URL query parameters, similar per connection attributes of other transport modes.

We also need to extend the web GUI connect modal to include these options.

**Comment by DC7IA** [comment]
What is the default bandwidth? What bandwidth am I currently using when connecting?

**Comment by martinhpedersen** [comment]
This was included in the v0.13.0 release 🎉
