### ISSUE TITLE
Drop support for Go 1.6

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#122]
Go 1.6 is [ancient](https://golang.org/doc/devel/release.html#policy) and stopped receiving security patches several years ago.

The reason to keep supporting it was to ensure that Pat could be compiled with the Go version available in debian stable backports.

Debian Stretch backports have Go 1.8 now.. so I guess that is a reasonable new minimum Go version.

**Comment by kitchen** [comment]
raspbian seems to ship with go 1.7 at least as of a few days ago when I got this all up and running.

**Comment by martinhpedersen** [comment]
Debian Buster (latest stable) includes Go 1.11, so I guess that would be a reasonable new minimum version.

**Comment by guitarpicva** [comment]
My Linux go version is 1.10.4 in a current Mint version, via the pkg mgr.  Mint is a very popular Ham platform.

Is the go upgrade process relatively painless?  I haven't tried it yet.

**Comment by martinhpedersen** [comment]
Thanks for the info :) I ended up keeping support for 1.10, so it should work just fine with the Go version shipped with Mint on rpi :+1: 

It's very easy install the official releases from golang.org actually. It's as simple as extracing a tarball and updating your PATH. It's the recommended way of installing Go, to get the latest features and fixes.

Instructions here if you want to give it a Go ;-) https://golang.org/doc/install#tarball

**Comment by guitarpicva** [comment]
Many/most are package hounds only however.  Keeping 1.10 for now if probably wise.
