### ISSUE TITLE
Pat connect with connect string fails

### ISSUE THREAD

**Issue by DC7IA** [la5nta/pat#126]
Hello,

`pat connect ardop:///HB9AK?freq=18114.4` produces the following result:

`zsh: no matches found: ardop:///HB9AK?freq=18114.4`

This seems to be an issue with Z-Shell. I wonder if other shells have similar issues.

Workaround: Using bash instead of z-shell. Not really a good solution for everyone using anything else than z-shell.

Possible solution: Make pat also recognize strings like "pat connect call HB9AK fre 18114.4", that should work on every shell.

73 Joshua DC7IA

OS: Ubuntu 16.04 LTS and Z-Shell

**Comment by martinhpedersen** [comment]
Hi Joshua,

it looks like you need to escape the zsh operator `?`, and possibly other operators as well.

This is not a Pat specific issue. Pat uses URI syntax for connect parameters, and you need to escape/quote them as you would with other generic URLs in zsh (and other shell languages).

I believe these two alternatives will work for zsh:
* `pat connect ardop:///HB9AK\?freq\=18114.4`
* `pat connect "ardop:///HB9AK?freq=18114.4"`


https://github.com/robbyrussell/oh-my-zsh/issues/31
https://apple.stackexchange.com/questions/254014/zsh-no-matches-found

**Comment by DC7IA** [comment]
Thank you.
