### ISSUE TITLE
Support Winlink HTML Forms

### ISSUE THREAD

**Issue by rpettigr** [la5nta/pat#135]
Having a choice of templates or being able to create your own template for composing messages so that pat can be used for easily sending ICS traffic or other emcomm traffic.

**Comment by rainerg2000** [comment]
@martinhpedersen I started adding support for composing messages based on templates. Similar to Winlink. So far it only supports the commandline. I added 'pat composeform'. See this branch https://github.com/rainerg2000/pat/tree/issue/135-support-ics-forms
It's not ready for pull request, but feel free to comment. 
Next steps (whenever I get a round to it)
- I think when Winlink creates a form-based message it attaches an XML file with the field values. Should add this feature
- Adding form support to the Pat web interface when composing a message

**Comment by xylo04** [comment]
Rainer, did you make progress? I'm inspired to start looking at the web side, and will try to integrate with your work.

**Comment by xylo04** [comment]
I see @rainerg2000's branch https://github.com/rainerg2000/pat/commits/issue/135-support-ics-forms has additional progress on both CLI and web.

**Comment by martinhpedersen** [comment]
Thanks @rainerg2000 :smile: 

Feel free to open av PR when you are ready for a proper review of the code. I will have a look at your branch soon :)

**Comment by rainerg2000** [comment]
I'm still on it, but it's far from being useful. It looks like I'll be able
to finish the work in a couple of weeks.
I'm currently working the interesting part where the Winlink form's submit
button passes data back to the message compose modal in Pat.

By the way, I wanted to use an accordion, so I first had to migrate jQuery
and Bootstrap to recent versions. That part is done. Unfortunately it's on
the same branch, and would have to be cherrypicked if you are interested in
it for other reasons.

Rainer.

**Comment by rainerg2000** [comment]
@xylo04 I overlooked your message from 3 days ago. I'll push my changes more frequently, so that you know where I'm at. I am currently integrating the form filling with Pat's message composer. There is a button on the message composer which let's you choose a form. It opens the form, the user fills it out and clicks 'submit' on the form. Then you're back on on Pat's msg composer, and can post it to the outbox.

If you're interested, you could work on generating the XML attachment that captures the form fields.   

Or you could add a feature for viewing a form-based message from the inbox. I have not put any effort into that part.

**Comment by rainerg2000** [comment]
@martinhpedersen @xylo04  This is a good version to look at: https://github.com/rainerg2000/pat/commit/4ae27874c8c9720f88ecdbf155b79eb40ed201ad
You'll need to download and unzip the Standard_Forms zip from winlink.org and then add a line in Pat's config.json, like:
"forms_path": "/Users/rainer/.wl2k/Standard_Forms"

Then go to the message composer dialog, and click the Template button on the bottom.

**Comment by rainerg2000** [comment]
@martinhpedersen @xylo04 I still have some loose ends to take care of, but all the features for authoring form-based messages are working now. I have extended the commandline and the web UI. Here's my latest commit: 
https://github.com/rainerg2000/pat/commit/2b2d63e5ac5746ceecfc605082c5fc1b058caddb
Next I'll test message compatibility with RMS Express. Can you help with that ? I don't have much experience with RMS Express. 

In the next few days I will create a pull request.

Additional features planned later:
- automatic download of newer form versions from winlink.org
- viewing form-based messages using the form template
- replying to a form-based message with the correct form-based reply template

KI7RMJ

**Comment by xylo04** [comment]
Yes, I can help with testing against Winlink Express. My personal email is on my GitHub profile, and my Winlink email should be obvious to construct. - K0SWE

**Comment by xylo04** [comment]
Pat to Winlink with an ICS 213 looks good. I'll send you one originating from Winlink next; should I send another 213 or can I try a different form?

**Comment by rainerg2000** [comment]
go for it, any form works, but Pat can't render it as a form yet.

**Comment by martinhpedersen** [comment]
@rainerg2000 FYI: I'm currently working on a code review of PR #197 
. Please don't make changes to that branch until I have completed the review :)

Thanks!

**Comment by rainerg2000** [comment]
Thank you. I'll wait. 
I have a bug fix that deals with form file names that contain spaces 
(like 'ARC 213 Message Initial Viewer')

**Comment by rainerg2000** [comment]
Another issue: 
Some forms are long names like "BC Initial Impact Assessment Form_Viewer.html". This runs into the 50 char limit for the attachment file name length. RMS Express requires the prefix 'RMS_Express_Form_' on the attachment name to recognize it as a form-based message.

The fix requires a change to https://github.com/la5nta/wl2k-go/blob/master/fbb/message.go
