### ISSUE TITLE
QSY with Hamlib off by 1Hz

### ISSUE THREAD

**Issue by posixPilot** [la5nta/pat#147]
Hi Martin,

I just started playing with Ardop and hamlib on Pat.  When setting up my connect aliases, I noticed that the frequency for one alias seems to get rounded down.  My alias with ?freq=14096.1 results in the radio tuning to 14.096.099, where as my alias with ?freq=14105.5 correctly tunes the radio to 14.105.500

I used tcpdump to sniff the payload of the Pat --> Hamlib network connection, and it seems that Pat is rounding down the frequency and asking Hamlib to set it to 14.096.099 (see bold text below):

21:05:00.570500 IP (tos 0x0, ttl 64, id 38282, offset 0, flags [DF], proto TCP (6), length 72)
    127.0.0.1.46864 > 127.0.0.1.4532: Flags [P.], cksum 0xfe3c (incorrect -> 0x0f41), seq 448829448:448829468, ack 2263984363, win 342, options [nop,n
op,TS val 245390932 ecr 245390932], length 20
        0x0000:  4500 0048 958a 4000 4006 a723 7f00 0001  E..H..@.@..#....
        0x0010:  7f00 0001 b710 11b4 1ac0 9808 86f1 a8eb  ................
        0x0020:  8018 0156 fe3c 0000 0101 080a 0ea0 5e54  ...V.<........^T
        0x0030:  0ea0 5e54 5c73 6574 5f66 7265 7120 3134  **..^T\set_freq.14**
        0x0040:  3039 3630 3939 0d0a                      **096099..**

  Thanks
  Mike

**Comment by martinhpedersen** [comment]
Thanks for the detailed report @posixPilot!

I have a lot on my plate right now, but will look into it as soon as possible.

Thank you!

**Comment by posixPilot** [comment]
Thanks, Martin!
