### ISSUE TITLE
ardop: support version 2

### ISSUE THREAD

**Issue by cbs228** [la5nta/pat#148]
Specifications for ARDOP version 2 were released 15 May 2018. This new version breaks both RF and TNC compatibility with ARDOP version 1. Since then, "beta" implementations have been released for Windows and Linux. Version 1 is still around, and at least some RMS nodes continue to operate it. But it is likely that version 2 is the future.

When attempting to `pat connect ardop:///...` with

  * Pat: `v0.6.0 (790d72c) linux/amd64 - go1.9.3` and
  * ARDOP: `Version 2.0.3.7-BPQ`,

pat fails immediately during the initialization phase with:

```
Unable to set ARQ bandwidth for ardop TNC: Syntax Err: ARQBW 2000MAX
```

The new [TNC specifications](https://ardop.groups.io/g/users/files/ARDOP_2) indicate that the options for this command have changed. There are probably other differences that will need to be addressed.

**Comment by cbs228** [comment]
This issue probably belongs in `wl2k-go` instead. I opened [#53](https://github.com/la5nta/wl2k-go/issues/53) there with a little more detail. I'll leave this issue open for now, but feel free to close it.

**Comment by cbs228** [comment]
The original ARDOP authors have reported an [issue](https://ardop.groups.io/g/users/message/4132) with the ARDOP2 modem:

> While ARDOP2 generally performs a bit better than ARDOP1 when stations are exactly on frequency the decode performance drops off rapidly if stations are more than a few Hz apart. With modern radios this may not be apparent, except perhaps on the higher bands (eg 10 Meters) but with older radios it may be impossible to get a connection.

The protocol is presently being reviewed for performance improvements. It is unclear whether future releases will use version 1 or version 2 of the TNC interface.

**Comment by martinhpedersen** [comment]
I'm seeing some mentions of an ARDOP 3, currently in development by Rick. The ARDOP project is moving so fast. I'm thinking maybe we should regard everything other than ARDOP 1 as experimental and wait until the project settles on a stable and widly adoped (node wise) version/branch/fork.

It's hard to keep up to date with the latest ARDOP development, since they don't have a public CVS. It would be great to find out if ARDOP 1 and 2 is still maintained, and if they have any ETA on ARDOP 3 and when they are planning to release it's host interface specification.

Any thoughts @cbs228?

**Comment by cbs228** [comment]
Given that ARDOP 2's development status is "withdrawn," there is no need to support it in Pat. As far as I am aware, Rick hasn't made any statements about how the v3 host interface will function. I think we should close this PR for now and not merge it… but if v3 looks a lot like v2, then this patch may be worth revisiting.

**Comment by martinhpedersen** [comment]
FYI: I've reverted the merge to support ARDOP 2 since it was withdrawn by the ARDOP developer(s). Thanks for the efforts anyway @cbs228 :)
