### ISSUE TITLE
No rig to QSY

### ISSUE THREAD

**Issue by geostant** [la5nta/pat#150]
Am I missing something here?

I'm trying to operate with ARDOP, I've not set a rig at all in the configuration as I don't want to CAT control my radio as I tune the dial freq manually.

I noticed that PTT_FORCE is false,
so why PAT insist that I've a rig setup?

**Comment by martinhpedersen** [comment]
Hi @geostant,

I am finding it hard to understand your issue. What exactly are you seeing and what do you expect?

Please include your config and log output as well.

Thanks!

**Comment by martinhpedersen** [comment]
I'm closing this due to lack of response. If this was a bug report, please re-open. Otherwise, the Community forum is a great way to get user support.

73 de LA5NTA
