### ISSUE TITLE
Web Gui - Allow column sorting

### ISSUE THREAD

**Issue by n4tqu** [la5nta/pat#154]
It would be nice to be able to sort on any of the columns in inbox, outbox, sent, date.

**Comment by xylo04** [comment]
Martin, do you have a strong opinion whether this should be done client side or server side?

**Comment by martinhpedersen** [comment]
No, not really.. but I have a feeling that client side would be easiest (no API changes) and probably more responsive.

What do you think?

**Comment by xylo04** [comment]
Sounds good to me. If pagination was in the API then that would affect the decision, but I don't see that so it's not a factor.
