### ISSUE TITLE
TH-D72A and gpredict not working

### ISSUE THREAD

**Issue by jrsphoto** [la5nta/pat#155]
I'm using rigctl 3.3 and I realize the TH-D72a driver is ALPHA but I was doing some testing for an upcoming project things didn't get off to a good start.  

I start things off with:
                       rigctld -m 233 -r /dev/ttyUSB0 -s9600 -vvvvv

that seems to start ok, and I'm seeing the typical calls go by and no error indications.

Then I launch gpredict where I have the radio configured in preferences as Duplex TRX, PTT Status=none, and VFO up/down is MAIN up/SUB down.

When I bring up the GPredict Radio Control panel and click Engage, it connects to rigctld but after several attempts and some errors, it fails and disconnects from rigctld.

I was just going to capture the output from the rigctld connection when the battery died on the HT so I'll do that tomorrow and post it here if anyone wants to see it.

Thanks

**Comment by martinhpedersen** [comment]
Hello!

Have you posted this to the wrong project? I can't see how this is related to Pat in any way.

**Comment by jrsphoto** [comment]
LOL.. Yes I sure did.  It was a late nite ;-)
