### ISSUE TITLE
Skip big messages

### ISSUE THREAD

**Issue by craigerl** [la5nta/pat#157]
Using HF, if somebody sends me a 20KB sized email, I'm pretty much locked out of my inbox as that would take 30 minutes to download.  All subsequent messages are unobtainable.  My scenario is summit-on-the-air, camping, etc.   I'd love to select which message to download, or, at a minimum, set a max-size in the config.json.

love pat!

-craig

**Comment by martinhpedersen** [comment]
Answered here: https://groups.google.com/d/msg/pat-users/r-sNNaQDprk/lAtA9bycCQAJ

Consider reopening this issue if it turns out that the features described in the answer (above) is not sufficient.

Thanks!

**Comment by martinhpedersen** [comment]
PS: As suggested by @craigerl, an option to prompt the user for each incoming proposal could be a good option in addition to the above described features. We could use the [PromptHub](https://github.com/la5nta/pat/blob/master/prompt_hub.go#L67) to implement this rather easily for both web gui and terminal.
