### ISSUE TITLE
ARDOP P2P Listen lockup

### ISSUE THREAD

**Issue by K3TL** [la5nta/pat#167]
Two P2P stations, both started in listen mode, station A connects to station B and checks for and exchanges email, all works correctly. Then station B tries to reconnect to station A with a reply, ARDOP connects but goes into idle mode. No attempt by PAT to check for messages. Requires a restart of PAT at station A. Seems as if Station A in no longer in Listen mode.

Reverse situation where B initiates to A and all works fine. Then when A reconnects to B and B goes into idle. Requires restart of PAT on Station B, then A can successfully connect to B and exchange email. 

Both stations running PAT V0.7.0 Go 1.13

**Comment by martinhpedersen** [comment]
> Hi Kevin,
> 
> That does not sound so good.. 
> 
> Did the issue appear in v0.7.0?
> 
> I'm going to need some logs from both stations to be able to figure this one out..
Could you run both pat instances with the env variable `ardop_debug=1` and send the output to me as separate files?
> 
> Run Pat like this: `ardop_debug=1 pat ....`
> 
> Please include a copy of the output the ARDOPDebug...log files as well.
> 
> Thank you!

(You can attach the log files to comments on this issue)

**Comment by martinhpedersen** [comment]
> Martin, Yes regarding the log files will do. 
> Did not notice this on V 0.6 but i may be able to test. 
> This is repeatable in V 0.7.0.
> 
> 73, Kevin

**Comment by K3TL** [comment]
Martin, 
This is the scenario: Sta A connects to B sends email and disconnects. Sta B replies to email then reconnects to Sta A. Sta A goes into idle. Sta B kills the connection and Sta A then stops and restarts PAT. Sta B then reconnects and passes the reply email.

Sta A pat log in two parts to capture the first part before being overwritten.


[P2P-Listen-Lockup-Logs.tar.gz](https://github.com/la5nta/pat/files/3673534/P2P-Listen-Lockup-Logs.tar.gz)

**Comment by martinhpedersen** [comment]
Thanks!

Could you also check if the issue is apparent in the previous version og Pat?

**Comment by K3TL** [comment]
I was able to set up station A with PAT v 0.6.1 but Sta B with PAT V0.7.0 and I get the same results.
if you prefer i can see if i have an older image for Sta B with v 0.6.1 on it and try again

**Comment by martinhpedersen** [comment]
If we could prove that the bug was introduced with v0.7.0, that would really narrow it down :)

I will have a look at the logs as soon as possible. Probably tomorrow evening (UTC+2)..

By the way, have you installed a new version of ARDOP recently?

**Comment by K3TL** [comment]
I found another machine with 0.6.1 on it and will test 061 to 061. 
Both of the test machines i used for the submitted logs have the latest piardopc V.1.0.4.1j

**Comment by martinhpedersen** [comment]
Excellent :)

If possible, please ensure that you perform the test using the same ardop version (V.1.0.4.1j) so wr can rule out issues due to changes in ARDOPc as well.

Thank you for helping out!

**Comment by K3TL** [comment]
confirmed exact same issue with v0.6.1
Sta A Pat v0.6.1 (a5c5d4c) linux/arm - go1.11.1 -- piardopc  1.0.4.1j-BPQ
Sta B Pat v0.6.1 (a5c5d4c) linux/amd64 - go1.6.2 -- ARDOPC 1.0.4.1j-BPQ
