### ISSUE TITLE
Connect to Direwolf via TCP KISS instead of AX25

### ISSUE THREAD

**Issue by bitmux** [la5nta/pat#171]
Direwolf exposes its KISS interface on port 8000 by default.  It is inconvenient at best to go through the installation of AX25 kernel module(s) and associated permissions issues (must run as root).  A modern web program such as PAT ought to be speaking KISS directly to the Direwolf "TNC."  This would enable GREATLY simplified setup for new users and clean up all the security issues of running user software as root.  Unfortunately I'm not a terribly good coder but will have a look myself at this.  Posting issue so that others will hopefully review and help me get this right!

**Comment by martinhpedersen** [comment]
Please see https://github.com/la5nta/wl2k-go/issues/56 and https://github.com/la5nta/wl2k-go/issues/57.
