### ISSUE TITLE
Add wiki page on how to hack on the source code

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#175]
Ref https://github.com/la5nta/pat/pull/173. We should add some wiki page to help new contributors how to hack on the source code.

Off the top of my head:
* Dependency management (using git submodules)
* How to maintain/update `bindata_assetfs.go` and the web sources
* How to add new transports
...

**Comment by xylo04** [comment]
I added a note about `go generate` to https://github.com/la5nta/pat/wiki/Building-from-source

**Comment by KI7ODK** [comment]
Yes, having some info on adding new transports would help me with adding AGW.

**Comment by martinhpedersen** [comment]
Tyler, I will add some info as soon as possible for you. I'll let you know when it's done.

**Comment by martinhpedersen** [comment]
https://github.com/la5nta/pat/wiki/Adding-transports

Hopefully enough to get you started :) Please let me know if you have further questions. I guess we can continue the discussion at https://github.com/la5nta/wl2k-go/issues/57, and hopefully we can remember to update the wiki as we go.

**Comment by martinhpedersen** [comment]
I think we have enough documentation covering this topic now:
* https://github.com/la5nta/pat/wiki/Building-from-source
* https://github.com/la5nta/pat/wiki/Adding-transports

Closing this 🎉
