### ISSUE TITLE
Ability to do tactical callsign option, template?

### ISSUE THREAD

**Issue by programmin1** [la5nta/pat#182]
How do I set a tactical callsign in Pat? 
I would like to use a tactical callsign and ICS-309 form template... it appears Pat does not have the option but I heard Winlink Express might?

I know JS and some web tech, is this something I might contribute in this area to to be able to do this?

**Comment by martinhpedersen** [comment]
Hi,

I'm glad you're willing to contibute to this project. Both these features have been discussed previously.

You can provide a list of auxiliary callsigns in the config file: https://github.com/la5nta/pat/blob/efd322d06404f7794b08bb854be09050cc941ace/cfg/config.go#L23

Using the CLI you can also override the From: field to match a aux_call. Thus you are able to send and receive messages with an tactical callsign:

```
pat compose
From [LA5NTA]: MY-AUX-CALL
To: LA1B
Cc: LE1OA
Subject: I'm sending this as MY-AUX-CALL
Press ENTER to start composing the message body.
```

The ability to override `From` is currently not available in the web gui. You are welcome to [send a PR](https://github.com/la5nta/pat/blob/master/CONTRIBUTING.md#code-contribution-guideline) with suggestions on how to implement this :)

Discussions related to tactical callsigns: https://github.com/la5nta/pat/issues/143, [Tactical Addresses/Callsigns @  pat-users](https://groups.google.com/forum/#!searchin/pat-users/tactical$20addresses%7Csort:date/pat-users/blfKf6Gl8PA/0xUhp7ULAAAJ), [Multiple Callsigns @ pat-users](https://groups.google.com/forum/#!searchin/pat-users/aux%7Csort:date/pat-users/zKgo8zyNY9Q/IjCr4x88CwAJ), 


Discussions related to Winlink forms: https://github.com/la5nta/pat/pull/76, [ICS forms? @ pat-users](https://groups.google.com/forum/#!searchin/pat-users/forms%7Csort:date/pat-users/twfX5qJZO_k/z78ut7P_CQAJ), [Winlink Express Forms @ pat-users](https://groups.google.com/forum/#!searchin/pat-users/forms%7Csort:date/pat-users/5LwYwHacoeE/qpR9hSDNCAAJ), [Forms @ pat-users](https://groups.google.com/forum/#!searchin/pat-users/forms%7Csort:date/pat-users/xvxabpM4m7c/FHVJiQSUAgAJ)

---------------

PS: This issue touches multiple topics. Our issue tracker is mainly for bug reports and discussions on specific feature requests. Please see our [issue tracker guidelines](https://github.com/la5nta/pat/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

For future general discussions and questions, please use the [pat-users](https://groups.google.com/group/pat-users) community list.

**Comment by xylo04** [comment]
Greetings,

As Martin mentioned before, tactical callsigns are known in Pat as auxiliary addresses and have been supported for some time.

In addition, Winlink forms have been recently added in v0.11.0!
