### ISSUE TITLE
Canno build on Debian 10 (Buster)

### ISSUE THREAD

**Issue by ClaudeMa** [la5nta/pat#183]
I need to recompile PAt because some command from PTC.go are not implemented in my Swiss-PTCII pactor III modem
When trying to compile i get this error

> Running tests...
can't load package: package _/home/claude/src/pat: cannot find package "_/home/claude/src/pat" in any of:
	/usr/src/_/home/claude/src/pat (from $GOROOT)
	/home/claude/go/src/_/home/claude/src/pat (from $GOPATH)
can't load package: package _/home/claude/src/pat/cfg: cannot find package "_/home/claude/src/pat/cfg" in any of:
	/usr/src/_/home/claude/src/pat/cfg (from $GOROOT)
	/home/claude/go/src/_/home/claude/src/pat/cfg (from $GOPATH)
can't load package: package _/home/claude/src/pat/internal/cmsapi: cannot find package "_/home/claude/src/pat/internal/cmsapi" in any of:
	/usr/src/_/home/claude/src/pat/internal/cmsapi (from $GOROOT)
	/home/claude/go/src/_/home/claude/src/pat/internal/cmsapi (from $GOPATH)
can't load package: package _/home/claude/src/pat/internal/gpsd: cannot find package "_/home/claude/src/pat/internal/gpsd" in any of:
	/usr/src/_/home/claude/src/pat/internal/gpsd (from $GOROOT)
	/home/claude/go/src/_/home/claude/src/pat/internal/gpsd (from $GOPATH)

pat source are in /home/claude/src/pat

Any idea?
Thanks
Claude

**Comment by harenber** [comment]
Hi Claude,

have you followed:

https://github.com/la5nta/pat/wiki/Building-from-source

?

Looks like the external packages are not checked out.

But it would interesting what PTC command gives you trouble. I am not
aware that SCS implemented any country-specific differences in the PTC
command set. If there is a bug in the PTC code, I would be happy to sort
it out and fix it.

Cheers

  Torsten DL1THM




Am 17.02.20 um 18:49 schrieb ClaudeMa:

**Comment by ClaudeMa** [comment]
Hi Torsten

Thank for you reply
External package are checked ou bu maybe a problem with env variable
I'm going to try to compile following your link

the Swiss-PTCII modem are modem build by SCHUEMPERLIN ENGINEERING AG under SCS licence
[http://www.schuemperlin.com/pages/ptc2a.htm](http://www.schuemperlin.com/pages/ptc2a.htm)
This modem is use by some ONG like Red Cross  and has only followings commands
Help command return

> ==================
> ADdlf     ANSwer    BC        BKchr     CHeck     CHOBell   CHOchr    CLr
> Connect   CSDelay   CTrlchr   CWid      CWSpeed   CWTerm    CWWeight  DAte
> DELete    DD        DIR       Discon    ESCchr    FEc       GRP       Help
> LFignore  LIN       LISt      Listen    LOg       LOGIn     LOCk      MAXDown
> MAXError  MAXSum    MAXTry    MAXUp     MYcall    MYSelc    MOde      MONitor
> NUL       Phase     PT        PUblic    QRTchr    Read      REMote    RESEt
> RESTart   SELFec    Send      SFile     SHow      SItor     STatus    SYStest
> Term      TIme      TR        TXDelay   Unproto   Version   Write
> 
> APower    AQrg      BRightn   FSKAmpl   MARk      MYLevel   PSKAmpl   RLe
> SERBaud   SPAce     TOnes     TRX       UPDATE    PACket    Gate      RCU
> HCr       PTChn     FAX       USer      PDuplex   PDTimer   TNC       XUser
> FREE
> 
> For more information type: Help <CMD> (eg: H Help)
> 
> cmd: 
> 

Trying to connect in pactor mode give 


> 2020/02/20 18:41:24 Pactor initialization failed: Command "CM 0" not accepted: 
> *** ERROR: PSE TYPE HELP
> 
> cmd: 

in modem.go string commands contains
> commands := []string{"MYcall " + p.localAddr, "PTCH " + strconv.Itoa(PactorChannel),
> 		"MAXE 35", **"CM 0"**, **"REM 0"**, **"BOX 0"**, **"MAIL 0"**, "CHOB 0", **"UML 1"**,
> 		"TONES 4", "MARK 1600", "SPACE 1400", "CWID 0", "CONType 3", "MODE 0"}
cmd in bold give error when sending in a terminal

maybe Swiss-PTCIIa and Swiss-PTCa has same commands

Cheers

Claude

**Comment by martinhpedersen** [comment]
I'm closing this issue now since we're drifting of topic. Please consider continuing the discussion on Swiss-PTC @ https://github.com/harenber/ptc-go. It sounds interesting :)

For further help regarding building Pat from source, please ask on the [pat-users](https://groups.google.com/forum/#!forum/pat-users) mailing list.

Thank you!

---------------

This issue touches multiple topics. Our issue tracker is mainly for bug reports and discussions on specific feature requests. Please see our [issue tracker guidelines](https://github.com/la5nta/pat/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

For future general discussions and questions, please use the [pat-users](https://groups.google.com/group/pat-users) community list.
