### ISSUE TITLE
PACTOR: Add support for additional connect URI parameters

### ISSUE THREAD

**Issue by la2fda** [la5nta/pat#187]
When using pactor modem, it is possible to put some extra commands for the modem in the custom_init_script. (i.e. fskampl 200)

my initscript with commands sent to modem:
txdelay 6
pskampl 600
fskampl 200

Some commands would be nice to set to different values according to which band or which station I am calling.

Is it possible and interesting to other than me, to be able to set multiple modem commands on the url and/or in the connect_aliases in the pat configuration file ?

BTW:
Thanks for your good work.

**Comment by martinhpedersen** [comment]
Hei Stein Henrik,

Yes, this would be useful for ARDOP sessions as well.. to configure the maximum bandwidth etc.

All of the URL paramenters are passed to the transport driver (in this case ptc-go), so it is certainly possible to implement specific connect parameters like this per transport. Maybe @harenber or @blockmurder can comment? :)

**Comment by martinhpedersen** [comment]
For reference: Here is a similar approach setting the packet baud rate on a per-connection basis, implemented by the ax25 package's serial-tnc scheme:
https://github.com/la5nta/wl2k-go/blob/master/transport/ax25/ax25.go#L130

**Comment by martinhpedersen** [comment]
Ping @harenber :-)

**Comment by harenber** [comment]
Will look into that, shouldn't be too complicated. @martinhpedersen please assign to me.

**Comment by harenber** [comment]
Pull request https://github.com/la5nta/pat/pull/190 updated to include this feature.
