### ISSUE TITLE
Can't crosscompile with ax25 library

### ISSUE THREAD

**Issue by ew1abz** [la5nta/pat#189]
Seems tags options don't work for packages when I'm using cross-compilation. It works perfectly if compilation is for the same machine/architecture.

Where are the problems: 
https://github.com/la5nta/wl2k-go/blob/master/transport/ax25/ax25_other.go
https://github.com/la5nta/wl2k-go/blob/master/transport/ax25/ax25_linux.go

Build constrains are in file names and in source code:
code:  `// +build libax25` `// +build !libax25`
file names: `ax25_linux.go` `ax25_other.go`

Crosscompilation commands:
```
export CGO_LDFLAGS="$(pwd)/.build/libax25-0.0.12-rc4/.libs/libax25.a"
export CGO_CFLAGS="-I$(pwd)/.build/libax25-0.0.12-rc4"
export GOARCH="arm"
export GOARM="7"
export GOOS="linux" 
go build -tags "static libax25" 
```

Same architecture compilation commands:
```
export CGO_LDFLAGS="$(pwd)/.build/libax25-0.0.12-rc4/.libs/libax25.a"
export CGO_CFLAGS="-I$(pwd)/.build/libax25-0.0.12-rc4"
export GOARCH=""
go build -tags "static libax25" 
```
go env (for crosscompilation):
```
GOARCH="arm"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOARM="7"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/home/user/go/src/github.com/la5nta/pat/.build/libax25-0.0.12-rc4" 
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="/home/user/go/src/github.com/la5nta/pat/.build/libax25-0.0.12-rc4/.libs/libax25.a"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build082456730=/tmp/go-build -gno-record-gcc-switches"
```
Library compiled for ARM (in case of crosscompilation) but id doesn't mater, because it even doesn't try to link it.
Error message:
```
go build -tags "static libax25" 
# github.com/la5nta/wl2k-go/transport/ax25
../github.com/la5nta/wl2k-go/transport/ax25/ax25.go:125:10: undefined: DialAX25Timeout
```

**Comment by martinhpedersen** [comment]
I've never tried crosscompiling with cgo enabled (I build all releases binaries on hosts with the correct arch and OS).

It would certainly be nice to be able to crosscompile it with libax25 support. Any help resolving this is greatly appreciated. Maybe someone could isolate the problem and read up on crosscompiling with cgo and statically linked C libraries?

**Comment by ew1abz** [comment]
Thank you, Martin. I'll ask Gophers in Slack. Unfortunately, your last Pat release (ARM binary) was compiled without AX25 support.

**Comment by martinhpedersen** [comment]
Thanks! The Google Group [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts) is also a good place to find answers.

But, really? The ARM deb of v0.9.0 does not include AX.25 support? I have not received any other reports of this, and it's been out for over a month now.

**Comment by martinhpedersen** [comment]
What makes you think that the offical deb for ARM does not provide AX.25 support?

```
$ pat version
Pat v0.9.0 (f52df2f) linux/arm - go1.13.8

$ md5sum /usr/bin/pat
17e9177d3f3838996220c1aae27bdd94  /usr/bin/pat

$ pat connect ax25:///LA1B
2020/03/29 11:19:02 Connecting to LA1B (ax25)...
2020/03/29 11:19:45 Unable to establish connection to remote: connection timed out
```

The last line (connection timeout) is because my radio is not hooked up currently. But it certainly shows that AX.25 is indeed provided in the ARM package (pat_0.9.0_linux_armhf.deb).

**Comment by ew1abz** [comment]
> pat_0.9.0_linux_armhf.deb
Let me double check, please.

**Comment by ew1abz** [comment]
@martinhpedersen I can confirm deb for ARM does provide AX.25 support. Sorry for the confusion.

**Comment by martinhpedersen** [comment]
Good to hear @ew1abz :slightly_smiling_face: 

I still think we should find a way to resolve the cross compilation issues, and write a section about it in on the wiki.

However, I think it's better for the project if I prioritize other tasks for the time being.

If you (or anyone else for that matter) are interested in investigating further, please let me know. Otherwise I will close this issue in a few days to keep the list tidy. We can always re-open in the future.

Thank you!
