### ISSUE TITLE
Package Pat for ARM64 on Raspberry Pi 4.

### ISSUE THREAD

**Issue by AJamesEdwards** [la5nta/pat#192]
Manjaro has an awesome and stable Arch based ARM 64bit Linux image for Raspberry Pi 3 and 4.
If you publish an Arm64 tar.gz package it can be consumed by "pacman" (the Arch package manager.)
Manjaro Arm64 also runs on PineBook and PinePhone

https://manjaro.org/features/fresh-and-stable/
https://manjaro.org/download/#raspberry-pi-4-xfce

**Comment by martinhpedersen** [comment]
Thanks for the suggestion @AJamesEdwards,

The current release process is rather cumbersome (I'm preparing all build artifacts manually), and this is the main reason why we don't publish more flavors at the moment.

However, if you would like to send a PR adding a script to easily build the required tarball for pacman, I'd be happy to consider it for future releases :)

**Comment by AJamesEdwards** [comment]
Consider using this tool
https://github.com/seletskiy/go-makepkg

**Comment by martinhpedersen** [comment]
I'm closing this one now, as no one has offered to help out with packaging. As pointed out earlier, all build artifacts are prepared manually and the release process is already rather time consuming. We have to prioritize the most popular distribution methods for now.
