### ISSUE TITLE
POP3 support

### ISSUE THREAD

**Issue by georges** [la5nta/pat#193]
Sorry if it's been suggested before (could not find in issues). Has POP3 support been considered? In a headless pat install, it would allow any existing email client to act as the UI.

**Comment by DC7IA** [comment]
I would instead like to suggest IMAP support. This makes it possible to then connect multiple client systems and let them all access the emails. POP3 really is a mess, you have then emails all over the place.

Also, as POP3 gets older, email clients start ending their support.

**Comment by martinhpedersen** [comment]
This seems to be related to issue #96 (possibly duplicate). See comments and feel free to continue the discussion there :)
