### ISSUE TITLE
Upgrading to version 9 from 8.

### ISSUE THREAD

**Issue by DdraigX** [la5nta/pat#194]
Just a quick question I couldn't find any basic information. I'm newish to linux so I wanted to ask. 

What's the best method of upgrading from version 8 to 9. Do I just install the .deb package? 

Thanks!

**Comment by martinhpedersen** [comment]
Hi,
yes you simply install the new deb package :)

PS: Please use the pat-users community group for these kinds of questions in the future. You'll find a link in the wiki and on getpat.io. This issue tracker is mainly for reporting bugs and discussing development related topics. Thank you!
