### ISSUE TITLE
Cannot Parse Outbox Message

### ISSUE THREAD

**Issue by RadioDavid10** [la5nta/pat#204]
I am using PAT on a Raspberry PI 3B+.  Recently I started getting the following message: "2020/06/17 15:57:23 Unable to parse message (/home/pi/.wl2k/mailbox/AC7DS/out/IU2TZTBZGAQS.b2f): EOF".

I upgraded from 0.6.0 to .0.9.0 recently.  I have been using the newer version for a while.  About 2 weeks ago it started giving me this error.  I have reinstalled PAT 0.9.0, but I am getting the same error. I also tried to use the terminal command line for messages, but received the same error.  

Thanks

David, AC7DS

**Comment by martinhpedersen** [comment]
I'm closing this one now. Please let us know if you still suspect this to be a bug in Pat. Thanks!
