### ISSUE TITLE
standards: Follow the XDG Base Directory Specification

### ISSUE THREAD

**Issue by DC7IA** [la5nta/pat#216]
Everybody likes standards in software, right?

So why not follow the XDG Base Directory Specification?

details: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Meaning pat should look for (and place) its configuration files by default under a directory in /home/$user/ instead of using its own path.

This leads to a less cluttered home directory.

**Comment by martinhpedersen** [comment]
> Everybody likes standards in software, right?
🥇 👍 

We already use the OS specific home directory:
https://github.com/la5nta/wl2k-go/blob/696b55ebe08cf2dbadba2ee294479a61b45c9678/mailbox/syncdir.go#L185

Do you mean some other sub-directory? Please be specific, and keep in mind that it would need to be portable to other platforms, such as Windows, macOS and Android/termux.

**Comment by DC7IA** [comment]
In the line you highlighted, this should be `.config/wl2k` instead of `.wl2k`, if you want to follow the standard for config files of applications in home directories.

This does not apply to macOS or Windows, since these operating systems organise user data in completely different ways.

**Comment by martinhpedersen** [comment]
Sure, I see what you mean. But we can't just move .wl2k inside .confg, since it contains more than just the config.

I guess we could move `~/.wl2k/config.json` to `$XDG_CONFIG_HOME/pat-config.json` or something, and the rest to `$XDG_DATA_HOME/pat/`. But we would need similar solution for the other operativ systems, preferably something that does not complicate stuff too much for the user.

The great think about the current implementation is that everyhing is placed in the same directory relative to the user's home directory, independent of OS. It makes it way easier to write wiki articles when we have a similar environment on all platforms, and the users have only one path to care about :)

**Comment by DC7IA** [comment]
>But we would need similar solution for the other operativ systems,

Why? This is a standard in the Linux world, it does not affect other operating systems. Plus every operating systems has their own unique way on how to store user configs and program data. :)

>The great think about the current implementation is that everyhing is placed in the same directory relative to the user's home directory, independent of OS.

Yes, but it also means home directories get more and more cluttered because some programs don't follow the standard.

>It makes it way easier to write wiki articles when we have a similar environment on all platforms, and the users have only one path to care about :)

Just put it in the documentation:

```
Windows: path/on/Windows (I don't use Windows, don't know the real path :D)
Linux: $XDG_CONFIG_HOME/wl2k/config.json for the config and $XDG_DATA_HOME/wl2k for the data
macOS: path/on/macOS
```

For every operating system, **their respective standards** should be followed.

Currently I have over 100 config directories in my home directory and over 80 config files. **It has been worse years ago**, but more programs seem to **start following the standard**. It has been much more. I just want a **clean home directory** and the configuration and data where they belong.

Ideally, when moving to a new Linux machine, or when reinstalling, you would simply copy over the content of X$XDG_CONFIG_HOME and all the setting would be the same, once that program is installed on the new machine. If every program stores their configuration in a different place, it gets increasingly annoying and difficult to find all the configurations.

Here you can find **a brilliant explanation**: https://farbenmeer.de/de/blog/the-power-of-the-xdg-base-directory-specification

Also, this question on StackExchange got some good answers: https://unix.stackexchange.com/questions/24347/why-do-some-applications-use-config-appname-for-their-config-data-while-other

**Comment by DC7IA** [comment]
The best way to transition would be:

if there is no config in $XDG_CONFIG_HOME; then look at the old path
if there is no config there either; then create config in $XDG_CONFIG_HOME
(or if the variable is not set the fallback would be to use ~/.config as per the standard)

This would **not require users to change anything themselves**, but instead would make pat follow the standard in the future. :)

**Comment by martinhpedersen** [comment]
I totally agree with you that it would be nice to adhere to this standard. The only problem I see is that it increases the complexity, both in code and usage when (and this is a big one) we take into account that this standard is currently only applicable to Linux.

If/when we decide to change the current implementation, we should take a look at this package: https://github.com/adrg/xdg.

**Comment by xylo04** [comment]
I'm starting to research how difficult this would be. Using https://github.com/adrg/xdg will make this significantly easier, but Pat's behavior is spread across two projects, https://github.com/la5nta/pat and https://github.com/la5nta/wl2k-go, e.g. [these methods](https://github.com/la5nta/wl2k-go/blob/407169b0733765d1c9b1938ab1ab6af12e90d40a/mailbox/syncdir.go#L172-L186). Still doable, but it needs a little more thought.

I see things falling into these directories:
* `XDG_CONFIG_HOME`
  * `config.json`
* `XDG_DATA_HOME`
  * `mailbox/`
  * `Standard_Forms/`
  * `rmslist.json`
* `XDG_STATE_HOME`
  * `pat.log`
  * `eventlog.json`
  * `last_version_report.json`

Does that sound about right? The good thing about using adrg/xdg is that all three will map to the same directory on Mac and Windows, preserving the current behavior (if not the current location).
* On Mac, all three are mapped to `~/Library/Application Support`
* On Windows all three are mapped to `%LOCALAPPDATA%` which resolves to something like `C:\Users\Chris\AppData\Local`

**Comment by martinhpedersen** [comment]
I'm glad we're finally moving forward with this issue 👍 

IMO it is important to provide some sort of transparent migration to the new directory structure for existing installations. Judging from the commit message, it looks like you're on top of that @xylo04 🙂

**Comment by xylo04** [comment]
PR is merged, and I also updated the wiki articles. This will be in the next release.

**Comment by DC7IA** [comment]
@xylo04 That's great to hear!

What's the best way to move my data and configuration to the new paths? :D

**Comment by DC7IA** [comment]
Also, I don't understand the code, does it do this?

```
$XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

$XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

$XDG_STATE_HOME defines the base directory relative to which user-specific state files should be stored. If $XDG_STATE_HOME is either not set or empty, a default equal to $HOME/.local/state should be used. 
```

That's really important since many distributions don't have variables set and just expect programs to use the defaults.

**Comment by xylo04** [comment]
> What's the best way to move my data and configuration to the new paths? :D

After we release v0.12, your files will be migrated by Pat on first run! Check out `MigrateLegacyDataDir()`.

> Is this supposed to be file system permissions?
> 
> ![grafik](https://user-images.githubusercontent.com/26351852/129917883-e366b1d2-7b30-4a16-ae0f-3875d2e1c4ca.png)
> 
> It looks like a typo to me, but I don't know anything about go. 🤔

Numbers prefixed with `0` are interpreted as octal, but prefixing with `0o` makes it more explicit. See https://github.com/golang/go/issues/151



> Also, I don't understand the code, does it do this?
> 
> ```
> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.
> 
> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.
> 
> $XDG_STATE_HOME defines the base directory relative to which user-specific state files should be stored. If $XDG_STATE_HOME is either not set or empty, a default equal to $HOME/.local/state should be used. 
> ```
> 
> That's really important since many distributions don't have variables set and just expect programs to use the defaults.

That logic is all in https://github.com/adrg/xdg, which I presume does the right thing in the absence of the environment variables. On all of the systems I tested (Ubuntu, RPi, Mac, Windows), it did the right thing. If you would like to get additional coverage of other distributions, perhaps you could help us beta test?
