### ISSUE TITLE
Feature: start rigctld automatically if it isn't running

### ISSUE THREAD

**Issue by DC7IA** [la5nta/pat#218]
That would be a huge improvement.

If we could have pat start rigctld automatically, this would save us from starting it by hand. :D 

Currently, I start pat, realize it does not set the frequency, ctrl+c pat (since there is no button "cancel connecting"), start rigctld (or set the frequency by hand) and start pat again.

**Comment by martinhpedersen** [comment]
I've been playing around with the idea of including a systemd unit file for this exact thing, similar to what we've done for the Pat daemon, ARDOP and kissattach.

Applications should not be responsible for spawning other applications though. That should be left to the operating system IMHO. But i totally agree with you that we should make it easier for users to start other important dependencies. Luckily, systemd is a great system to to that (on Linux).

Using udev rules users could even configure their systems to automatically start rigctld when the (usb) rig is connected to the machine. Instructions for that should probably be added in the wiki.

**Comment by martinhpedersen** [comment]
PS: If you always start rigçtld prior to launching Pat, you could write a quick script to do it for you. It would behave very similar to your suggestion of having Pat start it for you.

```bash
#!/bin/sh
rigctld -m 123 - s 9600 ... &
pat http
```

**Comment by DC7IA** [comment]
Could you provide more detail about the systemd unit you mentioned?

I've been looking for one in the documentation, but could not find anything.

Maybe add that to the wiki, so it is easy to find? :)

**Comment by martinhpedersen** [comment]
> Could you provide more detail about the systemd unit you mentioned?

No, sorry. It's currently only an idea. I have only written some to use on my own machines... they are too specific for my setup :/

But I am thinking a `/etc/default/rigctld` holding the configuration in addition to the systemd unit file.

PS: We should probably send a PR to hamlib requesting that they include it in future releases. They should really be part of the hamlib project IMHO.

**Comment by martinhpedersen** [comment]
Closing this now. We can continue the discussion in #221.

**Comment by martinhpedersen** [comment]
Have a look at this @DC7IA:
https://github.com/la5nta/pat/tree/b736afebe102caa41fdb8a84eec3736a09fec03e/share/rigctld 😄
