### ISSUE TITLE
Include systemd unit file for rigctld

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#221]
Following up on the discussion in issue #218.

Would be nice to include a systemd unit file for rigctld so users could autostart rigctld without having to write their own scripts.

Config could be read from `/etc/default/rigctld`. We could even add some udev examples on the wiki on how to autostart it when the rig is connected to the system.

**Comment by tobfromme** [comment]
I have created these on my home system and it seems to work just fine.

Files are:

/etc/rigctld.conf
[rigctl-systemd.zip](https://github.com/la5nta/pat/files/5758635/rigctl-systemd.zip)

/etc/systemd/system/rigctld.service

After copying these files into place and modifying /etc/rigctld.conf for your radio, do:

systemctl daemon-reload

systemctl start rigctld.service
