### ISSUE TITLE
GPS not seen by PAT

### ISSUE THREAD

**Issue by kd4jwf** [la5nta/pat#223]
gps not seen by PAT
pAT comfigure shows gpsd "true" but not seen ardop when trying to send position report

Build a PI used to upload PAT menu by km4ack and he recmmemded to contact this group for solution.

Kd4jwf
Jose
73

**Comment by martinhpedersen** [comment]
Hi Jose,

I'm not sure I understand your inquiry. Could you please provide some more details?

Please try to describe in details the **expected behaviour** and **the observed behaviour**. Some log output/screenshots would also be appreciated.

Thanks!

**Comment by kd4jwf** [comment]
Thank you for responding, the problem was with the GPS codes while using
Build a Pi from KM4ACK........it was not reading any data from GPS on Cody
and Position reporting for winlink.

Has been fix
