### ISSUE TITLE
exchange.go build failure (go get)

### ISSUE THREAD

**Issue by jeffpc** [la5nta/pat#241]
I have zero experience with go, so I have no idea how to even hack around this failure:

```
$ go get github.com/la5nta/pat
# github.com/la5nta/pat
.go/src/github.com/la5nta/pat/exchange.go:89:35: cannot use func literal (type func() (string, error)) as type func(fbb.Address) (string, error) in argument to session.SetSecureLoginHandleFunc
```

**Comment by martinhpedersen** [comment]
Thanks for the report 😊

What version of Go are you running? Please share the output of `go version`. Thanks!

**Comment by jeffpc** [comment]
No problem!  I'm using the go package from freebsd ports.

```
$ go version
go version go1.15.6 freebsd/amd64
```

**Comment by martinhpedersen** [comment]
Thanks!

I am able to reproduce this on macOS running Go 1.15.5. It looks like `go get` ignores the dependency versions listed in go.mod if you run it outside GOPATH (or something like that). I will have to read up on the Go Modules and go get docs and figure out if that is a feature or a bug.

Anyway, you should be able to build it by cloning the repo manually and running `go build`. Have a look at the wiki page for more details on how to build from source.

Thanks again for reporting this issue 😊

**Comment by jeffpc** [comment]
Confirmed.  Before I read the wiki, I did a quick test that seems to produce a `pat` binary:

```
$ cd $GOPATH/src/github.com/la5nta/pat
$ go build
```

Now to figure out how to actually use this ;)  Thanks.

**Comment by martinhpedersen** [comment]
Excellent :) Good luck!

PS: Enabling Go Modules explicitly by setting the env var `GO111MODULE=on` also seems to do the trick. Looks like it might be one of the caveats of using Go Modules 🤔

**Comment by jeffpc** [comment]
FWIW, `pat http` gives me the web UI.  So, the binary works at least a little bit.  I'll try to configure a rig tonight.  Thanks for your help.

I assume the `GO111MODULE=on` part was more for yourself rather than something you want me to try.

**Comment by martinhpedersen** [comment]
Yes, that last part was for future reference 😉

Sounds good. Good luck getting a rig (and modem) up and running on FreeBSD 😊

**Comment by martinhpedersen** [comment]
As of 37f73134d61e4dc9e1f9838a2caa802137aa323e we're requiring Go 1.16 or above, which has the behavior of `GO111MODULE=on` by default. The wiki page has been updated to mention the Go 1.16 requirement, so this will no longer be an issue :)
