### ISSUE TITLE
Attachments shall not be recompressed when the result file size is larger than the original.

### ISSUE THREAD

**Issue by ggramaize** [la5nta/pat#243]
### Tested version
Pat v0.10.0 (601f6d3) linux/amd64 - go1.15.1

### Reproduction path
- Run pat with the web server.
- On the web page, select "Action" > "Compose".
- Write an e-mail address and a subject
- Attach the following picture: 
![lena-vsmall.jpg](https://user-images.githubusercontent.com/5450075/109518305-6ad05800-7aaa-11eb-9713-bdbe09483f9f.jpg)
- Send the mail
- Open the mail in the outbox
- Download the attachment
- Check the file size

### Actual Behaviour
When attaching pictures to a mail, pat attempts to re-compress the file. 
Pat attaches the re-compressed file, even when the original file is smaller. 
Test vector size: 1.8KB
Attached file size: 3.5KB

### Expected Behaviour
When attaching pictures to a mail, pat attempts to re-compress the file. 
Pat attaches the original file when it is smaller. 
Test vector size: 1.8KB
Attached file size: 1.8KB

**Comment by martinhpedersen** [comment]
Yes, let's call this one a bug 😊

**Comment by martinhpedersen** [comment]
By the way, thanks for the detailed issue report and for providing an appropriate image to test with 👍
