### ISSUE TITLE
config fail on Raspberry PI 4

### ISSUE THREAD

**Issue by johanPO** [la5nta/pat#247]
I have an Pi4 that is up to date (apt-get update, upgrade and dist-upgrade done)
Download and installation works fine

sudo dpkg -i pat_0.10.0_linux_armhf.deb 
(Reading database ... 176249 files and directories currently installed.)
Preparing to unpack pat_0.10.0_linux_armhf.deb ...
Unpacking pat (0.10.0) over (0.10.0) ...
Setting up pat (0.10.0) ...
Processing triggers for man-db (2.8.5-2) ...

the pat configure command gives me 
error: Failed to locate the pattern.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pat/main.py", line 84, in main
    index = pat.locate(target, big_endian)
  File "/usr/local/lib/python3.7/dist-packages/pat/pat.py", line 88, in locate
    target=pattern, sets=self.sets))
KeyError: "configure Not Found In ['ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz', '0123456789']!"

using the /usr/bin/pat configure works

**Comment by martinhpedersen** [comment]
Hi!

It looks like you have another executable named `pat` installed on your system. Can you pleade share the output of running `which pat` and `echo $PATH` in your terminal?

Thanks!

**Comment by johanPO** [comment]
I dont remember anymore what it was that caused the issue. I found it and deinstalled the other package. Was something like pip3 uninstall Pat.. 
Maybe the point here is that a three letter name for the executable is more likely to cause issues than a longer one. Anyway, problem solved
