### ISSUE TITLE
AX.25: Exchange failed: unexpected EOF

### ISSUE THREAD

**Issue by ThreeSixes** [la5nta/pat#251]
Hello, I've been seeing that messages containing URLs and `!` characters fail to send with an `Exchange failed: unexpected EOF`. I have been able to reproduce this on both a local Winlink gateway, and with P2P packet connections to the most recent version of Winlink Express. In the case of the local gateway the operators were unable to find any error messages. Messages from others with URLs and `!` characters are received by Pat without any issue. The host is running Pat Winlink with the version string: `Pat v0.10.0 (601f6d3) linux/arm - go1.15.1`. I'm wondering if there's a character encoding / escaping issue. In both cases there is a very strong and clear signal, and repeated attempts to send the same messages fail while other messages that don't contain these strings and characters successfully send.

Connection logs for the local Winlink gateway:
```
WELCOME TO PORTLAND AMATEUR RADIO CLUB'S WINLINK PACKET GATEWAY - CN85RK
[WL2K-5.0-B2FWIHJM$]
;PQ: 67992075
CMS via W7LT >
>FC EM SYU3KJJATGOQ 228 202 0
Sending checksum 49
FS Y
Remote accepted SYU3KJJATGOQ
Transmitting [Bad chars] [offset 0]
2021/06/06 22:51:41 Exchange failed: unexpected EOF
```

Contents of `SYU3KJJATGOQ.b2f`:
```
Body: 6
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=ISO-8859-1
Date: 2021/06/07 05:49
From: K7JLX
Mbo: K7JLX
Subject: Bad chars
To: SMTP:joshlucy@gmail.com
Type: Private

!!!!
```

P2P session logs:
```
2021/06/06 22:32:43 Connecting to K7AJK-0 (ax25)...
2021/06/06 22:32:45 Connected to K7AJK (AX.25)
;FW: K7AJK
[RMS Express-1.5.37.0-B2FHM$]
K7JLX DE K7AJK >
>FC EM YYP2G7ZUDV44 295 245 0
Sending checksum 6A
FS Y
Remote accepted YYP2G7ZUDV44
Transmitting [Bad char test.] [offset 0]
2021/06/06 22:34:42 Exchange failed: unexpected EOF
```

The P2P session had the same content as the message to the local gateway. Previous attempts to send a message with a single `!` anywhere in the body failed, and so did any message that contained a URL with an `unexpected EOF error`.

**Comment by ThreeSixes** [comment]
By a character encoding issue I mean the following - It seems that the page itself loads as UTF-8 when I look at the page properties and I'm wondering if we're hitting an issue where the message content is actually UFT-8 formatted despite the `Content-Type` header being sent in the e-mail specifying `ISO-8859-1`. Maybe detecting and setting the encoding to `UTF-8` might solve the problem, or conversely converting the e-mail to the specified char set specified by the e-mail's Content-Type header would solve the problem.

**Comment by martinhpedersen** [comment]
Thanks for the detailed report @ThreeSixes 🙂 

I don't think this is related to the character encoding (UTF-8 vs ISO-8859-1), because the message body is always translated from UTF-8 to ISO-8859-1 before being wrapped in the B2F message structure.

The message transferred over the air as compressed binary data. Maybe the binary string is somehow treated as a command by your TNC, or something like that...

To rule out any TNC issues, can you try to reproduce the issue by sending the same content over "telnet" (tcp/ip) and report back?

Thank you!

**Comment by ThreeSixes** [comment]
This doesn't happen over telnet, but I'm now wondering if the issue isn't
with the TNC. I'll report back once I can test.

**Comment by ThreeSixes** [comment]
Looks like tweaking TNC settings helped a lot. There's still more troubleshooting required, but I think I have it! Thanks!
