### ISSUE TITLE
Exchange failed: Bad SID line

### ISSUE THREAD

**Issue by drboone** [la5nta/pat#252]
Pat doesn't seem to like this pending mail line:
```
2021/06/07 07:00:49 Got connect (ax25:KE8CYC-15)
2021/06/07 07:00:49 Connected to KE8CYC-15 (AX.25)
;FW: KE8CYC
[RMS Express-1.5.37.0-B2FHM$]
; KB8ZQZ DE KE8CYC (EN72QP)
;PM: KB8ZQZ 6C68SHYXNP11 643 KE8CYC [PAT didn't work
2021/06/07 07:01:36 Exchange failed: Bad SID line: ;PM: KB8ZQZ 6C68SHYXNP11 643 KE8CYC [PAT didn't work
```
I'm hypothesizing that it's about the [ character.  I can't find any documentation worth mentioning on the format of these PM lines, so it's hard to tell what should be valid there.

Note that the sender is current RMS Express.

**Comment by martinhpedersen** [comment]
Nice catch @drboone 🥇 😄 

You're absolutely correct regarding the `[` character. We need to change how the SID line is captured.

The buggy line is here: https://github.com/la5nta/wl2k-go/blob/master/fbb/handshake.go#L90. Should probably change it to something like this:
```go
switch {
case strings.HasPrefix(line, `[`) && strings.HasSuffix(line, `]`):
...
}
```

Would also be great to include some tests for this part of the handshake, and in particular this example.

**Comment by drboone** [comment]
Martin,

In this example, at the point the offending line arrives, the relevant SID has already been processed, yes?  Is there a reason to keep scanning for SIDs after the first one?  (I lack adequate experience here.)

I ask because it seems like a subject line like `[Pat-0.10.0-B2FHMG$] didn't work` would foil even the `strings.HasSuffix()` test.

**Comment by martinhpedersen** [comment]
Ideally we should probably ignore subsequent SID lines after the initial one, or throw an error. But my proposed solution requires the line to start with the character `[` and end with an `]`, so it would never match a subject line or any other valid sentence apart from a SID 🙂 

You're example of a "subject line" would be sent by the remote station like this:
> `;PM: KB8ZQZ 6C68SHYXNP11 643 KE8CYC [Pat-0.10.0-B2FHMG$] didn't work`

That sentence would be caught by the default condition of the switch, and be silently ignored (as it is an unsupported protocol extension introduced by Winlink Express).

**Comment by drboone** [comment]
Oh, I see, the existing code says "contains", not "prefix".

**Comment by drboone** [comment]
A problem with a local node is interfering with my ability to test the suggested change with my cross-town test partner.  Will keep trying and report results when I can.
