### ISSUE TITLE
Add a good default value for forms_path

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#256]
We should add a good default value for forms_path, so that no configuration is needed to get started with html forms.

Since all other state is stored under the .wl2k directory, I think that is a good place to put it.

Similar to fConfigPath, fLogPath, fMailboxPath... it should probably be defined as a CLI option (fOptions) with a default value relative to appDir rather than a config parameter. (See main.go)

@xylo04 @rainerg2000 - What do you think?

Relates to #254, #233 and #234.

**Comment by xylo04** [comment]
Agreed, this would be another good thing to prioritize before the release. I'll work on this shortly.
