### ISSUE TITLE
Building PAT over ARM64

### ISSUE THREAD

**Issue by UgoPoddine** [la5nta/pat#266]
Hello,

I would like to install the pat client over an ARM64 RaspberryPI3 image.
Must I start from the master version eb00df2 ? 
Is there some caveat to follow ?

Thank-you
73 Ugo

**Comment by xylo04** [comment]
Hi Ugo,

There shouldn't be anything unique about compiling on ARM64, just follow the build guide at https://github.com/la5nta/pat/wiki/Building-from-source. Starting from the `master` branch will be the most stable. You're also welcome to use the `develop` branch if you're willing to be a beta tester, just be aware that there may be more bugs there.

If you run into any problems, feel free to reach out to us on this issue or on pat-users@googlegroups.com.

73, Chris
