### ISSUE TITLE
Are you doing Hacktoberfest?

### ISSUE THREAD

**Issue by programmin1** [la5nta/pat#284]
Is this repo participating in Hacktoberfest - I find this project useful and if you want to encourage attention and progress on it you can add the "Hacktoberfest" tag for developers to find it.

**Comment by xylo04** [comment]
I don't see any reason why we shouldn't participate. All that seems to be required of us is to *either* tag the repo with `hacktoberfest` *or* tag merged PRs with `hacktoberfest-accepted`. It's low burden for maintainers, and participants get game points for contributing high-quality PRs. It's a win-win situation.

**Comment by programmin1** [comment]
That's right, if your repo has the "hacktoberfest" label (added in the gear icon area at the right of the page https://github.com/la5nta/pat then it should be one that people will find.
Good work on this project and I support it though I haven't really learned GOlang.

**Comment by martinhpedersen** [comment]
I've added hacktoberfest as a topic now. Let's see what happens 👍
