### ISSUE TITLE
Support for non-interactive message sending from the command line

### ISSUE THREAD

**Issue by bseidenberg** [la5nta/pat#297]
I'd love to be able to compose messages non-interactively, via command line arguments. I'd envision this as something looking like this:

`pat compose [-r <callsign>] [-s <subject>] [-a </path/to/attachment> ] [-c <cc-addr]> recipient-address [...]`

with -a and -c being repeatable and the text of the message coming in from STDIN. (This pretty much matches the syntax for mail/mailx).

This would allow for scripting Pat, as well as for use cases where other programs want to compose and exchange messages.

**Comment by bseidenberg** [comment]
@martinhpedersen Before I spend some time learning go and such, are you amenable to this?

**Comment by martinhpedersen** [comment]
@bseidenberg I really like this idea and your proposed syntax 👍

I'd be happy to include this functionality in Pat 🙂 

PS: I have a feeling we might need to do some refactoring of the compose code. Maybe a good start would be to implement the cli stubs without implementing the actual message construction. Then we could look into refactoring the existing code afterwards. Just a suggestion, without looking too much into the code 🙂

**Comment by martinhpedersen** [comment]
Resolved in v0.12.1.
