### ISSUE TITLE
pat_0.12.0_windows_i386 executable missing .exe extension

### ISSUE THREAD

**Issue by jschollenberger** [la5nta/pat#298]
The windows binary seems to be missing its ".exe" extension:

```% unzip -l pat_0.12.0_windows_i386.zip
Archive:  pat_0.12.0_windows_i386.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2021-10-31 12:49   pat_0.12.0_windows_i386/
 14917096  2021-10-31 12:49   pat_0.12.0_windows_i386/pat
---------                     -------
 14917096                     2 files
```

The documentation and help text still have it so I think this is a regression from v0.11.0 which does have an extension. If not, I'd be happy to update the docs.

**Comment by martinhpedersen** [comment]
Thanks for reporting this 👍 

I have uploaded a new zip archive to replace the broken one. Should be fixed now 🙂
