### ISSUE TITLE
pat deletes /tmp folder after updating templates

### ISSUE THREAD

**Issue by kd2qar** [la5nta/pat#300]
Rather than just deleting the downloaded file pat attempts to delete the entire /tmp folder on linux. This (hopefully) fails on most systems but I am running pat in a Docker container and noticed that the entire /tmp folder was missing after a while. The problem is in the "forms.go" file where it gets the temp folder and then deletes the entire folder and contents after downloading the file. I suggest it would be better just to delete the downloaded file. The current method could have some problematic issues on a live system if the delete succeeds.

--- forms.go    2021-12-01 07:09:54.146309883 -0500
+++ forms.go    2021-12-01 07:11:38.535008838 -0500
@@ -332,10 +332,11 @@
                filename = fileRe.FindStringSubmatch(dispo)[1]
        }
        dir := os.TempDir()
-       defer os.RemoveAll(dir)
+//     defer os.RemoveAll(dir)
        zipBytes, _ := io.ReadAll(resp.Body)
        defer resp.Body.Close()
        zipFilePath := path.Join(dir, filename)
+       defer os.RemoveAll(zipFilePath)
        err = os.WriteFile(zipFilePath, zipBytes, 0o600)
        if err != nil {
                return fmt.Errorf("can't write update ZIP: %w", err)

The os.RemoveAll() function ( as documented for go) removes both the folder AND the contents.

I have tested the above changes and it solves the issue and cleanly removes the downloaded file only.
-Mark

**Comment by xylo04** [comment]
Hmm, this looks like my bad. I meant to pair this with `os.MkdirTemp` in order to have a temporary subdirectory that I could delete, but I didn't actually do that.

**Comment by martinhpedersen** [comment]
🙂 

I will create a PR for this, which also cleans up a few other things related the download function.

Thanks for reporting this @kd2qar 👍
