### ISSUE TITLE
"--callsign" flag not recognized in pat compose v0.12.1

### ISSUE THREAD

**Issue by AG7GN** [la5nta/pat#310]
The new compose features in v0.12.1 are much appreciated. Thank you! It works great, except that the `--callsign`, `-r` flag is not recognized.

I'm running pat on Raspberry Pi RaspiOS Bullseye 64-bit

```
pi@buildpi64:~ $ pat version
Pat v0.12.1 (ccb4934) linux/arm64 - go1.17.3

pi@buildpi64:~ $ pat compose help
compose - Compose a new message.
	If no options are passed, composes interactively.
	If options are passed, reads message from stdin similar to mail(1).

Usage:
  compose [options]

Options:
   --callsign, -r    Callsign to send from. Default reads from config
   --subject, -s     Subject
   --attachment , -a Attachment path (may be repeated)
   --cc, -c          CC Address(es) (may be repeated)
                     Recipient address (may be repeated)
```
When I specify  the callsign with `-r`:

```
pi@buildpi64:~ $ echo "Message content" | pat compose -r AG7GN --subject "Test message" me@example.com
unknown shorthand flag: 'r' in -r
Usage of compose:
  -a, --attachment stringArray   
  -c, --cc stringArray           
  -s, --subject string           
unknown shorthand flag: 'r' in -r
```
Same when using `--callsign`:
```
pi@buildpi64:~ $ echo "Message content" | pat compose --callsign AG7GN --subject "Test message" me@example.com
unknown flag: --callsign
Usage of compose:
  -a, --attachment stringArray   
  -c, --cc stringArray           
  -s, --subject string           
unknown flag: --callsign
```

73,
Steve/AG7GN

**Comment by martinhpedersen** [comment]
Thanks for reporting 👍 

This was introduced in PR #297.

IMO i think this should be removed in favor of the existing global `--mycall` option. This would place the message in the outbox associated with the given callsign, but I think this would be less ambiguous.

If we for some reason want to allow composing of messages with a custom sender address, then `--from` would be a better name IMHO. This is more in tune with the teminology of the Winlink messaging format, and would be less ambiguous with regards to which outbox it is posted to.

**Comment by martinhpedersen** [comment]
The feature is available in the interactive composer, however referred to [as "from"](https://github.com/la5nta/pat/blob/ccb493474debb2a84ee2ab60b292327426c86f8a/cli_composer.go#L30).

I think we should implement this for the non-interactive composer as well, as `--from`.

The `--callsign` option is totaly lacking in the implementation, it is just mentioned in the usage text.

**Comment by AG7GN** [comment]
Thanks for the prompt reply, Martin. My use case is that I manage 2 Winlink accounts on the same Raspberry Pi, and I want some email to originate from one account and some from another. After some experimentation, I landed on this solution:

My "default" Winlink account is AG7GN. The other is WA7VMC. I created 2 `config.json`
files, one for each account. I symlinked `config.json` to `config.json.AG7GN`.

```
pi@buildpi64:~/.config/pat $ ls -al
total 16
drwxr-xr-x  2 pi pi 4096 Dec 12 12:43 .
drwx------ 16 pi pi 4096 Dec  7 11:07 ..
lrwxrwxrwx  1 pi pi   17 Dec 12 12:43 config.json -> config.json.AG7GN
-rw-------  1 pi pi 1340 Dec 12 12:33 config.json.AG7GN
-rw-------  1 pi pi 1340 Dec 12 12:34 config.json.WA7VMC
```

When I want to send mail from AG7GN:

```
pi@buildpi64:~ $ echo "Message text from AG7GN" | pat compose --subject "Test from AG7GN account" me@example.com
Message posted
pi@buildpi64:~ $ pat --send-only connect telnet
```

When I want to send mail from WA7VMC:

```
pi@buildpi64:~ $ echo "Message text from WA7VMC" | pat --config /home/pi/.config/pat/config.json.WA7VMC compose --subject "Test from WA7VMC account" me@example.com
Message posted
pi@buildpi64:~ $ pat --config /home/pi/.config/pat/config.json.WA7VMC --send-only connect telnet
```

This works as expected. If you implemented `--from` the way you envisioned, would it automatically select the correct `config.json` file? 

73,
Steve/AG7GN

**Comment by martinhpedersen** [comment]
> This works as expected. If you implemented --from the way you envisioned, would it automatically select the correct config.json file?

No, not at all. Thats the ambiguity I mentioned 😅 

It sounds like you want to control the `mycall` configuration. That can be achieved with the global `--mycall` option. It allows you to override the mycall value from the config file each time you invoke the application.

Something like this:

```
# This will post a message to the local WA7VMC outbox
echo "hello" | pat --mycall WA7VMC compose --subject "Test from WA7VMC account" me@example.com

# This will connect via telnet using the WA7VMC account and the WA7VMC mailbox folder
pat --mycall WA7VMC connect telnet
```

But please not that you are now switching between two different sets of mailboxes. If you run `pat --mycall WA7VMC http` you will get WA7VMC's messages listed in the web gui. If you run `pat --mycall AG7GN http` you will get AG7GN.

(Your symlink solution is also perfectly valid, and adds even more flexibility in terms of other config changes between the two accounts).

**Comment by AG7GN** [comment]
Ah, I see. The tactical address feature would be useful. 

Using `--mycall` would cause pat to prompt for a password, correct? Since I'm using this feature in scripts run via cron, it's easier to have separate `config.json` files for each account. I can see where `--mycall` might be useful in other cases, though.

-Steve/AG7GN

**Comment by bseidenberg** [comment]
Whoops. I started with the help text,  as I got further, I realized --mycall already existed, and decided to use it instead, but never updated the help text. I hadn't realized the password issue.

@martinhpedersen Can you point me a bit at where the password config for tactical calls comes from and I'll look into that? I've never used one. I can add a --callsign or --from (I think we should keep -r as the shorthand to match existing mail(1) implementations on *Nix) soon.

**Comment by martinhpedersen** [comment]
Ah, I see 🙂 

I think we should go with `-r, --from` which should only affect the From header in the message. We only need to add the non-interactive eqvivalent of https://github.com/la5nta/pat/blob/ccb493474debb2a84ee2ab60b292327426c86f8a/cli_composer.go#L30..L35 to do so. The default should be to use thr value of mycall.

The --mycall option affects much more than only the message sender address. It is used over the air to identify the station, and also as the winlink "account" during authentication with CMS to download inbound messages.

There is nothing in the protocol keeping us from setting a sender adress (the message header `From`) to a different value than the callsign of the station. Just like with SMTP, winlink messages' sender address does not have to match the authenticated user. In fact, Winlink CMS will gate your message even if you set it to a gmail address for instance... but the message will probably end up in the spam filter or worse 😅

As I said, setting the From address to anything but the winlink account callsign or any of it's tactical addresses does not make much sense. So we should probably mention this in the usage text.

**Comment by bseidenberg** [comment]
Makes sense. Will get to that shortly.

**Comment by martinhpedersen** [comment]
Btw, please don't feel obligated to implement this. I don't want contributors to feel like they need to take responsibility just because they contributed to related code. Contributing should be fun, and happen on the contributor's terms. I'd be happy to fix this myself if you prefer 🙂 

That said, it should be an easy fix, by copying the code from my link above 👍

**Comment by bseidenberg** [comment]
Understood. I want to feel invested, no worries.  This likely may be needed for my project anyway.

**Comment by martinhpedersen** [comment]
Thanks! It's greatly appreciated 🙂 

If you haven't seen it already, this shows that your PR was highly appreciated by the community: https://youtu.be/Nx1tt-5YCwg ❤️

**Comment by bseidenberg** [comment]
Ooohh.... I had not! Thank you for sharing!
