### ISSUE TITLE
Can we handle interrupts in listen.go instead of exhange.go?

### ISSUE THREAD

**Issue by harenber** [la5nta/pat#314]
Hi @martinhpedersen ,

for the PACTOR listen mode, I have to set the modem into the WA8DED hostmode as soon as Pat is started with "-l pactor". However, when the user ends Pat with CTRL-C, the pactor driver is only notified when a current exchange is going on (signal handler in exchange.go), not when no connection was active. So there is no way to set the modem back to terminal mode. While this is not a problem for Pat (the PACTOR driver can handle this), it may be confusing for the user.

edit: probably listen.go is also not a good place, as we need the interrupt when the user aborts a connect as well. Is there a upper method than would be suitable?

Cheers

  Torsten

**Comment by martinhpedersen** [comment]
Hi Torsten,

You should be able to restore the modem to initial state in the Close() method. It is called by the cleanup function, as a deferred function call from main().

https://github.com/la5nta/pat/blob/ccb493474debb2a84ee2ab60b292327426c86f8a/main.go#L331

https://github.com/la5nta/pat/blob/ccb493474debb2a84ee2ab60b292327426c86f8a/main.go#L479


If `Close()` is not called prior to app exit, then we have a bug to investigate 😊

**Comment by martinhpedersen** [comment]
On second thoughts, I'm pretty sure we have bugs related to graceful shutdown. Ideally the main [HandleFunc](https://github.com/la5nta/pat/blob/ccb493474debb2a84ee2ab60b292327426c86f8a/main.go#L360) call should return successfully on each run, but I know of at least a couple of cases where this is not true.

We'll have to investigate this further. From the top of my head - A good place to start would be to catch the interrupt signal in the `func main()` and gracefully cancel the running command through a [context cancellation](https://pkg.go.dev/context) or another similar approach. We would also need to eliminate any call to `os.Exit` (this includes `log.Fatal`) across the app, and get rid of the interrupt signal handling in connect.go. It's a rather big task, but IMHO the best solution to this problem.

Here is a related article on the topic: https://rudderstack.com/blog/implementing-graceful-shutdown-in-go/

I fear we'll just have to live with this for a while, until we can fix this properly throughout out the app.

As for ptc-go, I think you should implement it as if `pModem.Close()` is always closed before app termination. Then I can start looking into improving the graceful shutdown behavior 😊
