### ISSUE TITLE
Provide deb package for Librem 5 (linux/arm64 phone)

### ISSUE THREAD

**Issue by programmin1** [la5nta/pat#318]
I am unable to install Pat on Librem 5 Linux Phone.
I try the ARM DEB file installer and select to install it after download, I get:

Unable to install pat: 
Error while installing package: package architecture (armhf) does not match system (arm64)

I can't find the right .deb installer to install on this one?
And I imagine all the Pinephone users and users of every other Linux phone are having a similar issue installing on their computers.

**Comment by xylo04** [comment]
Hi @programmin1, we haven't targeted `arm64` in the past, only `armhf` for Raspberry Pi. I believe you're the second I've heard requesting that architecture. If we do get more folks interested, we could provide a .deb installer.

In the meantime, your best recourse would be to [build from source](https://github.com/la5nta/pat/wiki/Building-from-source).

**Comment by programmin1** [comment]
Okay. Would those work on a computer with only 3GB RAM or do I have to do some sort of crosscompilation on the bigger computer?

**Comment by xylo04** [comment]
Building from source should be fine on arm64 and 3GB of RAM, it will compile on Raspberry Pis with 1 or 2 GB.

**Comment by martinhpedersen** [comment]
Not sure, but the arm64 deb we are planning for Raspberry Pi OS (#321) will work on this platform as well? 🤔 

Please try one of the deb files shared in #321 and report back. Thank you! 🙂

**Comment by programmin1** [comment]
Pat seems to work but its browser interface breaks and freezes upon selecting "post" a message on my Librem Phone (amber) - maybe I need to flash a newer version of Librem5 OS. I compiled Pat myself but unfortunately not so useful for this reason.

Has anyone had good success debugging a frozen web page within the Librem Phone browser?

**Comment by martinhpedersen** [comment]
The web browser issue is unrelated to the question of providing a compatoble .deb. Let's hope a newer version of the OS solves this.

Did you test any of the .deb files I mentioned, or have you only tried woth your custom build?

**Comment by martinhpedersen** [comment]
I'm closing this one now. It should in theory be covered by #321. If not, I would say we need to find out how many potential users we have that would use this before committing to adding a new build target for this.
