### ISSUE TITLE
Unable to get frequency, QSY failed

### ISSUE THREAD

**Issue by k7bls** [la5nta/pat#320]
Pat 0.12.1, ARDOP, IC-7300
proc rigctld: 0, pid: 5898, args:  -m 3073 -r /dev/ttyUSB0 -p /dev/ttyUSB0 -P RTS -s 19200
proc piardopc: 0, pid: 5336, args:  8515 pcm.ARDOP pcm.ARDOP -c /dev/ttyUSB0 -p /dev/ttyUS

Audio works, PTT works, but not QSY

2022/02/08 15:58:51 Unable to get frequency from rig IC-7300: code -1.
2022/02/08 15:58:51 Listening for incoming traffic on ardop...
2022/02/08 15:58:51 Starting HTTP service (http://localhost:8080)...
2022/02/08 15:58:51 ARDOP TNC (ARDOP TNC_1.0.4.1j-BPQ) initialized
2022/02/08 15:59:52 QSY failed: unable to get rig frequency: read tcp 127.0.0.1:45328->127.0.0.1:4532: i/o timeout

73 Brian K7BLS

**Comment by martinhpedersen** [comment]
Thanks for the detailed log output. It looks like Pat is unable to communicate with your rigctld instance (on port 4532). This is most likely an issue with your setup and/or rigctld, and not a bug in Pat.

It looks like you're telling both rigctld and ardopc to communicate with your rig over the same tty (/dev/ttyUSB0). This will not work, and should produce an error from either rigctld or ardopc.

Please re-post this at the pat-users mailing list. I'm sure you will get some help to sort this one out 🙂
