### ISSUE TITLE
Remove WINMOR support

### ISSUE THREAD

**Issue by xylo04** [la5nta/pat#331]
The WINMOR transport protocol has been [deprecated for over a year](https://winlink.org/content/winmor_deprecated). There are basically no more RMS stations still offering it. We should remove it from the available transports.

**Comment by martinhpedersen** [comment]
Does anyone know if has been completely removed from Winlink Express?

I'm worried some users might still rely on this for P2P nets. But if it's already removed from Winlink Express then I agree that we should do the same 🙂

**Comment by xylo04** [comment]
WINMOR has been removed from Winlink Express, too.
<img width="708" alt="image" src="https://user-images.githubusercontent.com/389971/159127378-7cf90f16-5509-4aef-b78c-7de4f33449bc.png">

**Comment by martinhpedersen** [comment]
Thanks for the screenshot :)

Yes, I agree.. let's remove it 👍

**Comment by DC7IA** [comment]
> There are basically no more RMS stations still offering it. We should remove it from the available transports.

Yay, finally let that proprietary tech die. :)

**Comment by DC7IA** [comment]
![image](https://user-images.githubusercontent.com/26351852/164014151-bf762f46-a5cc-4bd5-b84d-6b439ae90b5b.png)

@martinhpedersen Please remember to update the website to no longer advertise something that is going to get removed soon.
