### ISSUE TITLE
Add --p2p-only to pat compose

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#334]
> Is it possible to set the P2P flag when using compose from the command line? Not interactive mode, but something that could be used in a script.
> 
> 73, de @km4ack

**Comment by DC7IA** [comment]
What would this do?

**Comment by martinhpedersen** [comment]
> What would this do?

Set the P2P flag on the composed message, so it will be ignored in CMS sessions and only send through P2P sessions.
