### ISSUE TITLE
idea: support WEFAX and RTTY reception features of PTCs

### ISSUE THREAD

**Issue by DC7IA** [la5nta/pat#350]
Maybe pat could also support reception of WEFAX and RTTY using PTCs, currently there's no software for Linux, BSDs or MacOS that allows using these features.

PTCs are quite good at decoding WEFAX and RTTY.

As pat can be used for emergency communication, this would be a useful addition, weather data can be helpful in emergency situations.

**Comment by martinhpedersen** [comment]
I think these features are out of scope the project. Pat is a Winlink client app, and tries to follow the unix philosophy of smaller composable applications as opposed to monolithic design.

As such, IMO such features should be implemented as separate applications. Possibly  by utilizing the rich set of libraries that Pat is composed of. For instance, the Pactor code is implemented as an isolated package exposing the modem connectivity in a clean and idiomatic Go API for app developers to use :)

I can see why it would be tempting to add such features, but feature creeping is very hazardous to software projects like these IMHO.

**Comment by martinhpedersen** [comment]
I would love to see apps for these features though. So if you or anyone else decides to start working on it, please let the rest of us know. I'm sure we could help each other out 😊
