### ISSUE TITLE
Can't type on phone

### ISSUE THREAD

**Issue by programmin1** [la5nta/pat#354]
The Pat http compose window is not letting me type - in Gnome Web browser, the default browser in Librem 5.

I have updated it and not sure if this is something I need to report elsewhere??

**Comment by martinhpedersen** [comment]
AFAIK, none of the mainstream web browsers have this issue. It's certainly an edge case, but it would be interesting to know if the bug is in our code or the browser you are using.

If anyone with access to this browser care to debug and fine the root cause, feel free to post your findings 🙂

**Comment by programmin1** [comment]
I had tried it later and it was working.
