### ISSUE TITLE
Add VARA listener for inbound (P2P) connections

### ISSUE THREAD

**Issue by wf5w** [la5nta/pat#369]
I use pat winlink on my raspberry pi.

I have wine and box86 and am able to run Vara FM.

We are using p2p to a simplex frequency.

1. I cannot set listen mode to vara FM

2. Furthermore, I cannot (using the http client at least) listen to vara FM without putting in a call sign in the target box.

I can receive messages if I initiate the connection first.

This makes listening for any email from anyone trying to send to impossible.

Jerry

**Comment by xylo04** [comment]
Hi Jerry, listen mode for the VARA driver is still in progress, sorry for
the inconvenience. We're working on it!

**Comment by olewsaa** [comment]
Will listener mode be added for VARA HF also ? P2P in HF mode is also something some of us wants.

**Comment by martinhpedersen** [comment]
Yes, it will cover both HF and FM 👍
