### ISSUE TITLE
Pat restarting during VARA HF connection. 

### ISSUE THREAD

**Issue by km4ack** [la5nta/pat#371]
Pat = 0.13.0
Mint = 20.3
VARA = 4.6.3

When attempting a VARA HF connection, the radio keys twice and then Pat restarts. You can see it happening in [this video](https://youtu.be/XY_hhH7a9ZQ). Downgraded to Pat 0.12.1 from the Google folder and the issue disappeared. Using 0.12.1 it connects to the gateway as expected.

**Comment by martinhpedersen** [comment]
Are you able to capture the log output from the terminal from before the restart? I suspect it's a script that restarts Pat, and the actual error is masked by the log file truncation when Pat is (re)started.

Thanks!

**Comment by km4ack** [comment]
**Started the connection**
km4ack@km4ack:~$ pat connect varahf:///KN4CCQ
2022/09/09 07:53:00 my-rig ready. Dial frequency is 7.100.00 MHz.
2022/09/09 07:53:00 Connecting to KN4CCQ (varahf)...

At this point it keyed the radio twice and locked in TX on the third attempt. Then spit out the following error:

panic: runtime error: slice bounds out of range [11:10]

goroutine 13 [running]:
github.com/n8jja/Pat-Vara/vara.(*Modem).handleCmd(0xc00028c120, {0xc0000a2060, 0xa})
	/go/pkg/mod/github.com/n8jja/!pat-!vara/vara@v0.0.0-20220513234311-0b0963c08629/vara.go:232 +0x3b0
github.com/n8jja/Pat-Vara/vara.(*Modem).cmdListen(0xc00028c120)
	/go/pkg/mod/github.com/n8jja/!pat-!vara/vara@v0.0.0-20220513234311-0b0963c08629/vara.go:191 +0x1ef
created by github.com/n8jja/Pat-Vara/vara.(*Modem).start
	/go/pkg/mod/github.com/n8jja/!pat-!vara/vara@v0.0.0-20220513234311-0b0963c08629/vara.go:99 +0xaa

**Comment by martinhpedersen** [comment]
That's perfect Jason, thank you :)

Looks like we have an out-of-range slice error in the vara code then. @xylo04 do you mind having a look? 😊 (I'm currently on vacation 🏖️)

**Comment by martinhpedersen** [comment]
Looks like the REGISTERED response has been cut short for some reason 🤔

                        log.Printf("Full speed available, Vara registered to: %s", c[11:])

**Comment by martinhpedersen** [comment]
Maybe it would be safer to use strings.Cut when splitting strings like this.

Anyway, strange that VARA responds with a REGISTERED without callsign. It is clearly documented to include the callsign.

**Comment by martinhpedersen** [comment]
On second thoughts, maybe strings.Split instead. strings.Cut is only available in newer Go versions.

**Comment by km4ack** [comment]
After reading @martinhpedersen response, I reinstalled 0.13.0 AND entered my VARA credentials in VARA HF. This time it worked as expected so it appears to only have the issue for an unregistered VARA user.
