### ISSUE TITLE
Using pat for Yeasu 891 

### ISSUE THREAD

**Issue by fjmj1238** [la5nta/pat#383]
I am using a 2010 macbook running 10.13.6 to control a Yeasu 891 HF radio.   Loaded all software per the instructions in this section and all worked except control of the radio:      ref: 

  Last login: Thu Dec  8 18:54:54 on ttys002
fred--MacBook-2:~ fjmj1238$ pat connect
2022/12/08 19:24:40 Unable to get frequency from rig my_precious_rig: dial tcp [::1]:4532: connect: connection refused.
Missing argument, try 'connect help'.
fred--MacBook-2:~ fjmj1238$ 

Not totally sure what I have done wrong.  The program will work great for "telnet"  if I command:  pat telnet    It just will not connect to the USB com  to the radio.....I do have other programs running on the same computer that will connect just fine to the radio.

**Comment by martinhpedersen** [comment]
Hi!

This error suggests that rigctld is not running, or not listening on that interface/port.

Can you please share the command you are using to start rigctld?

**Comment by fjmj1238** [comment]
rigctld -m 1036 -r /dev/ttyUSB0 -s 4800      This as suggested begins the dameon to be used in pat.  I am connected to the radio (FT-891) by usb cable and am using a soundBlaster USB sound card.  All are working fine with the JT8 software programs so far.

**Comment by martinhpedersen** [comment]
Hmm.. that's a different error condition on your second attempt. It seems it was able to connect, but then reached i/o timeout when trying to get a response from one of the commands sent to rigctld.

Can you please provide some more details into how you start rigctld, including it's log output?

I'm pretty confident that this is a system misconfiguration, because Pat is using a very well tested and production-grade TCP socket interface to communicate with rigctld, and all the errors you are receiving are generic i/o errors from the TCP/IP layer 🤔

**Comment by fjmj1238** [comment]
I am thinking you are asking for the file pat.log.....If so after inputting same as above got this from pat.log:
2022/12/12 00:37:20 Unable to get frequency from rig my_precious_rig: read tcp [::1]:53093->[::1]:4532: i/o timeout.

seems the same....maybe you have a different log location in mind.

**Comment by martinhpedersen** [comment]
No, I ment rigctld's log/terminal output.

Try running it in verbose mode like this `rigctld -vvvv -m 1036 -r /dev/ttyUSB0 -s 4800` and provide the full output. Thanks :)

**Comment by fjmj1238** [comment]
OK:   Last login: Mon Dec 12 08:15:39 on ttys000
fred-jacobss-MacBook-2:~ fjmj1238$ rigctld -vvvv -m 1036 -r /dev/ttyUSB0 -s 4800
rigctld.c(652) Startup: rigctld -vvvv -m 1036 -r /dev/ttyUSB0 -s 4800
rigctld Hamlib 4.5 Sat Oct 29 23:39:41 2022 +0000 SHA=58f9fd
Report bugs to <hamlib-developer@lists.sourceforge.net>

Max# of rigctld client services=32
yaesu: initrigs4_yaesu called
rig_init(558): 0x7f904e00881c rs->comm_state==0?=0
rig_init: rig has VFO_A
rig_init: rig has VFO_B
rig_init: rig has VFO_MEM
ft891_init called, version 20221025.7
 1:newcat.c(467):newcat_init entered
 1:newcat.c(507):newcat_init returning(0) 
 1:rig.c(807):rig_open entered
rig_settings_load_all: settings_file (/Users/fjmj1238/.config/hamlib_settings): No such file or directory
rig_open: cwd=/Users/fjmj1238
rig_open: /Users/fjmj1238/hamlib_settings does not exist
serial_open: /dev/ttyUSB0
serial_open(229): open failed#1
serial_open(229): open failed#2
serial_open(229): open failed#3
serial_open(229): open failed#4
serial_open: Unable to open /dev/ttyUSB0 - No such file or directory
port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory
rig_open: rs->comm_state==0?=0
 1:rig.c(1013):rig_open returning(-6) IO error

Opened rig model 1036, 'FT-891'
rig_open: error =  1:newcat.c(467):newcat_init entered
 1:newcat.c(507):newcat_init returning(0) 
main: twiddle=0, uplink=0, twiddle_rit=0
 1:rig.c(807):rig_open entered
rig_settings_get_path: path=/Users/fjmj1238/.config/hamlib_settings
rig_settings_load_all: settings_file (/Users/fjmj1238/.config/hamlib_settings): No such file or directory
rig_open: cwd=/Users/fjmj1238
rig_open: /Users/fjmj1238/hamlib_settings does not exist
rig_open: async_data_enable=0, async_data_supported=0
serial_open: /dev/ttyUSB0
serial_open(229): open failed#1
serial_open(229): open failed#2
serial_open(229): open failed#3
serial_open(229): open failed#4
serial_open: Unable to open /dev/ttyUSB0 - No such file or directory
port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory
rig_open: rs->comm_state==0?=0
 1:rig.c(1013):rig_open returning(-6) IO error

IO error
 /dev/ttyUSB0 No such file or directory 
Backend version: 20221025.7, Status: Stable
 1:network.c(977):network_multicast_publisher_start entered
network.c(981):multicast address=0.0.0.0, port=4532

This from System Report:
CP2105 Dual USB to UART Bridge Controller:

  Product ID:	0xea70
  Vendor ID:	0x10c4  (Silicon Laboratories, Inc.)
  Version:	1.00
  Serial Number:	00DE3592
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Silicon Labs
  Location ID:	0x06400000 / 1
  Current Available (mA):	500
  Current Required (mA):	100
  Extra Operating Current (mA):	0

**Comment by fjmj1238** [comment]
I am thinking I will have to recompile pat using tags as suggested in guide....I have no way to know how to do this.

**Comment by fjmj1238** [comment]
Did a fresh install of hamlib and pat on another similar macbook and got this:
fred-jacobss-MacBook:~ fjmj1238$ rigctld -vvvv -m 1036 -r /dev/ttyUSB0 -s 4800
rigctld.c(653) Startup: rigctld -vvvv -m 1036 -r /dev/ttyUSB0 -s 4800
rigctld Hamlib 4.5.1 Thu Dec 08 15:11:46 2022 +0000 SHA=75fbd0
Report bugs to <hamlib-developer@lists.sourceforge.net>

Max# of rigctld client services=32
yaesu: initrigs4_yaesu called
rig_init: rig_model=Yaesu FT-891
rig_init: rig has VFO_A
rig_init: rig has VFO_B
rig_init: rig has VFO_MEM
ft891_init called, version 20221204.7
 1:newcat.c(469):newcat_init entered
 1:newcat.c(509):newcat_init returning(0) 
 1:rig.c(812):rig_open entered
rig_settings_load_all: settings_file (/Users/fjmj1238/.config/hamlib_settings): No such file or directory
rig_open: cwd=/Users/fjmj1238
rig_open: /Users/fjmj1238/hamlib_settings does not exist
serial_open: /dev/ttyUSB0
serial_open(229): open failed#1
serial_open(229): open failed#2
serial_open(229): open failed#3
serial_open(229): open failed#4
serial_open: Unable to open /dev/ttyUSB0 - No such file or directory
port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory
rig_open: rs->comm_state==0?=0
 1:rig.c(1018):rig_open returning(-6) IO error

Opened rig model 1036, 'FT-891'
rig_open: error =  1:newcat.c(469):newcat_init entered
 1:newcat.c(509):newcat_init returning(0) 
main: twiddle=0, uplink=0, twiddle_rit=0
 1:rig.c(812):rig_open entered
rig_settings_get_path: path=/Users/fjmj1238/.config/hamlib_settings
rig_settings_load_all: settings_file (/Users/fjmj1238/.config/hamlib_settings): No such file or directory
rig_open: cwd=/Users/fjmj1238
rig_open: /Users/fjmj1238/hamlib_settings does not exist
rig_open: async_data_enable=0, async_data_supported=0
serial_open: /dev/ttyUSB0
serial_open(229): open failed#1
serial_open(229): open failed#2
serial_open(229): open failed#3
serial_open(229): open failed#4
serial_open: Unable to open /dev/ttyUSB0 - No such file or directory
port_open: serial_open(/dev/ttyUSB0) status=-6, err=No such file or directory
rig_open: rs->comm_state==0?=0
 1:rig.c(1018):rig_open returning(-6) IO error

IO error
 /dev/ttyUSB0 No such file or directory 
Backend version: 20221204.7, Status: Stable
 1:network.c(977):network_multicast_publisher_start entered
network.c(981):multicast address=0.0.0.0, port=4532

Not sure what is going on...pat http returns the gui expected.  Just will not communicate with the radio for some reason.

**Comment by fjmj1238** [comment]
I reloaded hamlib because I could not find the hidden file name "hamlib_settings".  After reload, I still could not find the file with that name in any directory on my computer loaded with hamlib.  I found file lname "rigs" but no file that the above out put suggested was the target.   Should I rename the file that is now "rigs" to "hamlib_settings"?

**Comment by lilo-chita** [comment]
_serial_open: Unable to open /dev/ttyUSB0 - No such file or directory_

Rigctld can't connect to your 891. Is ttyUSB0 port correct?

**Comment by martinhpedersen** [comment]
Yes, this definitely looks like either a hamlib issue/misconfiguration. Closing this issue now. You should be able to get help in the pat-users mailing list, or from other hamlib users.
