### ISSUE TITLE
web: Compose modal hight issue

### ISSUE THREAD

**Issue by srb6101** [la5nta/pat#392]
Ok, after looking at the faq , not seeing the issue,

I am using linux mint on a  toshiba laptop. 
I installed pat the .12 version
when i open the compose message window up, i can add the to field, subject and the message itself.

However the message window opens about a 1/4 of the way down the screen. 

I can not drag it around, or do anything else with it. 

how do i then save the message to the outbox? 

are the save buttons below the area i can see?

Or am i totally missing something here

Stephen

KK6ZJC

**Comment by martinhpedersen** [comment]
Can you provide some screenshots please?

Also, which browser are you using?

Thanks!

**Comment by srb6101** [comment]
Ok, I attached 2 pictures of what i see on my screen

I am unable to grab the top of the window to move it, however i discovered that if i press the function key (instead of control) and end then i can get it to move down to the bottom of the window.

It seemed kind of a weird way to do it instead of being able to resize the window to fit the wcreen.

Possible an update feature in the future?

the browser i am using is firefox which is why i attempted to grab the window to move it

Stephen KK6ZJC     On Saturday, February 18, 2023, 10:29:29 PM PST, Martin Hebnes Pedersen ***@***.***> wrote:  
 
 


Can you provide some screenshots please?

Also, which browser are you using?

Thanks!

**Comment by xylo04** [comment]
Stephen, any chance you could post those screenshots through the [GitHub issue interface](https://github.com/la5nta/pat/issues/392)? Your email attachments did not come through. Thanks!

**Comment by srb6101** [comment]
![Screenshot from 2023-02-19 20-15-19](https://user-images.githubusercontent.com/125767358/220191111-1487f109-c8fe-416b-a96e-adbe2f33c1a5.png)
![Screenshot from 2023-02-19 20-14-59](https://user-images.githubusercontent.com/125767358/220191112-ad8fcb51-beff-43b8-883f-18011a04029e.png)

**Comment by martinhpedersen** [comment]
It looks like your screen resolution is too low to be able to display the entire height of the compose modal. Can you try zooming out in the browser (`ctrl` + `-`)?

**Comment by martinhpedersen** [comment]
We should probably fix this somehow at some point. Possibly by reducing the `<textarea>` if we don't have enough room for the buttons.

But as a work-around, zooming out should do the trick.

**Comment by martinhpedersen** [comment]
@srb6101 Did you find a solution to your problem? Did zooming out help?

**Comment by srb6101** [comment]
yes i did figure it out finally everything works now properly
     On Wednesday, April 19, 2023, 10:42:38 PM PDT, Martin Hebnes Pedersen ***@***.***> wrote:  
 
 


@srb6101 Did you find a solution to your problem? Did zooming out help?
