### ISSUE TITLE
Forms - General - GPS   adding characters to Time variable

### ISSUE THREAD

**Issue by jedijf** [la5nta/pat#393]
The position report for AJ3DI has not been entered due to the following error(s):

Date/Time: 2/26/23=20 is not a valid date or time...

The '=20'   gets added

**Comment by jedijf** [comment]
EASY FIX (cause I did it)

.txt   has an extra space at time variable

GPS Position Report.txt

Extra space at end of this line:
Time: <var thetime>

**Comment by martinhpedersen** [comment]
So there is a bug in the forms file `GPS Position Report.txt` then? Is that you conclusion?

**Comment by jedijf** [comment]
Yes.

There is an extra space on the "TIME" line after the end bracket for
thetime varaible.

<thetime>_       <----

On 2/28/23, Martin Hebnes Pedersen ***@***.***> wrote:
> So there is a bug in the forms file `GPS Position Report.txt` then? Is that
> you conclusion?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/la5nta/pat/issues/393#issuecomment-1447850416
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
jim fisher
Jedijf
AJ3DI
www.aj3di.com
HamshackHotline ext: 14423
"Do, or do not. There is no 'try.'"
  --  Jedi Master Yoda

**Comment by jedijf** [comment]
Actual line:

Time: <var thetime>_    <--  _ is the space

remove the space.

On 2/28/23, Jim Fisher ***@***.***> wrote:
> Yes.
>
> There is an extra space on the "TIME" line after the end bracket for
> thetime varaible.
>
> <thetime>_       <----
>
> On 2/28/23, Martin Hebnes Pedersen ***@***.***> wrote:
>> So there is a bug in the forms file `GPS Position Report.txt` then? Is
>> that
>> you conclusion?
>>
>> --
>> Reply to this email directly or view it on GitHub:
>> https://github.com/la5nta/pat/issues/393#issuecomment-1447850416
>> You are receiving this because you authored the thread.
>>
>> Message ID: ***@***.***>
>
>
> --
> jim fisher
> Jedijf
> AJ3DI
> www.aj3di.com
> HamshackHotline ext: 14423
> "Do, or do not. There is no 'try.'"
>   --  Jedi Master Yoda
>


-- 
jim fisher
Jedijf
AJ3DI
www.aj3di.com
HamshackHotline ext: 14423
"Do, or do not. There is no 'try.'"
  --  Jedi Master Yoda

**Comment by martinhpedersen** [comment]
Got it. Thanks! 👍

IMO our parser should be clever enough to handle trailing/leading spaces. Adding it to the TODO list.

**Comment by xylo04** [comment]
Agreed, we have to treat the form templates as immutable since they are published by WDT; we're just consuming them and need to deal with them as they are.

**Comment by jedijf** [comment]
So just to help further...the txt files are static...so this is more of a typo in that static txt file....

But you folks know way more than I do, this is what it seems to me.

**Comment by martinhpedersen** [comment]
Looked a bit closer into this. It's clearly a bug in the form file and/or the system parsing the produced message. The template has a whitespace character after the `<var thetime>`, which we preserve. I don't think it's a good idea to remove trailing whitespace from the message body by default.
