### ISSUE TITLE
Updating Forms data requires a page reload in http mode

### ISSUE THREAD

**Issue by guitarpicva** [la5nta/pat#396]
Is there a way to force this as part of the update process?

**Comment by xylo04** [comment]
I've been dreaming of doing something more elegant, but since I've never gotten around to doing that, just reloading the page is better than the current state.

**Comment by guitarpicva** [comment]
If it's just JavaScript should be pretty easy to force a page reload.

--
Mitch, AB4MW

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by guitarpicva** [comment]
> I've been dreaming of doing something more elegant, but since I've never gotten around to doing that, just reloading the page is better than the current state.

If you are building HTML5 (JS DOM object model) and/or using WebSockets, in-place updates with no reload should be possible.

**Comment by guitarpicva** [comment]
Greetings Martin,
Been a while since we played with pat and the pactor modems.

I have been trying to run down the Winlink new password process for the OTA exchange.

Is that documented anywhere that you know of??
Regards,
Mitch
ab4mw

--
"The challenge is stratospherically beyond me, and yet I am not being asked for initiative but response." -- J.D. Walt

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
