### ISSUE TITLE
go install not working on g 1.20.4

### ISSUE THREAD

**Issue by w1jp** [la5nta/pat#407]
Installing on macOS 13.3.1a with go 1.20.4:

```
% go install github.com/la5nta/pat@latest
go: downloading github.com/la5nta/pat v0.14.1
go: github.com/la5nta/pat@latest (in github.com/la5nta/pat@v0.14.1):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by martinhpedersen** [comment]
Yes, we had to take a shortcut when releasing the latest patch. It's a hotfix for a bug in a separate repo, so we ended up releasing with a replace directive in go.mod.

It's already fixed on develop. But until it's merged into master, you can do `go install github.com/la5nta/pat@28e98e8` which is more or less the same as v0.14.1, minus the replace directive and a typo 😊
