### ISSUE TITLE
Web UI is not clearing To/CC fields after a message is Posted to Outbox

### ISSUE THREAD

**Issue by amatecha** [la5nta/pat#408]
I have a 100%-reproducible bug where, when I post a message to my Outbox, and then go to Compose a new mail, the "To" and "CC" text boxes still contain the recipients I specified in the last mail.

**Software environment**
Linux Mint 21.1 Vera
Pat version 0.14.1 (62ac29e)
Firefox 112.0.2 64-bit

**Steps to repro:**

Click "Action" -> "Compose..." menu
Add a recipient in "To:" field
Add a subject and message
Click "Post" to post it to Outbox
Click "Action" -> "Compose..." menu

**Expected result:**
Completely blank Compose window contains no pre-filled data

**Actual result:**
Recipient of previously-composed mail is still present in "To:" field

Please let me know if there's any other info I can provide to help diagnose the issue.

**Comment by martinhpedersen** [comment]
Thanks for reporting this 👍 I'm able to reproduce on Brave Browser as well.
