### ISSUE TITLE
Windows Defender identifies zip as threat

### ISSUE THREAD

**Issue by cartpauj** [la5nta/pat#415]
Downloaded with latest Google Chrome. Failed virus protection: https://prnt.sc/3VsDLGFSpKT-

**Comment by martinhpedersen** [comment]
Ah, here we go again 😞 

* https://github.com/la5nta/pat/issues/103
* https://betterprogramming.pub/a-big-problem-in-go-that-no-one-talks-about-328cc3e71378
* https://go.dev/doc/faq#virus

**Comment by martinhpedersen** [comment]
Not much we can do about this unfortunately. If it feels unsafe, my recommendation is to build Pat from source.. but you'll probably end up with the same false positive.

**Comment by cartpauj** [comment]
Sorry, I didn't spot the duplicate with #103 . I'll close this issue.

**Comment by martinhpedersen** [comment]
No problem at all. I appreciate the report, as I was not aware that this was still a thing. Thanks 😊
