### ISSUE TITLE
Yaesu via WinLink:  machine refuses message.

### ISSUE THREAD

**Issue by Monkaya** [la5nta/pat#416]
Hello Winlink sysops!
    -
    I am a new user, wrestling to make Winlink Express operational!
    I have apparently OPENED Ports 8773 and 8772, allowing communication
    BUT
    Winlink Express session gets this from (destination?) machine:
   
*** Connecting to RMS Relay at 127.0.0.1 port 8772
*** Connection failed: No connection could be made because the target machine actively refused it 127.0.0.1:8772
*** No connection to RMS Relay (127.0.0.1 port 8772) at 2023/06/22 00:12 UTC

    Can you please help me figure out what needs fixing to make Winlink Express work via internet and hopefully HAM radio

   **EQUIPMENT**
   HAM Radio:    Yaesu FT-5100 mobile
                            with mini stereo jacks:  1 - DATA in out.   2 - External SPEAKER.
    TNC:        Digirig mobile
    Connection method:  Winlink telenet
    Computer Operating System:    Windows 10

     |\,/|
    < * * >  Thank You!  Hoppy trails!
      \_/
       -  Bret (aka 'Monkaya')  --  KF7VRU

**Comment by martinhpedersen** [comment]
Hi there!

This is th bug tracker for Pat, an alternative Winlink client mainly used for platforms other than Windows.

To get support from the Winlink Development Team and Winlink Express, please see this page: https://winlink.org/content/user_support_and_help.

73
