### ISSUE TITLE
`pat compose` in non-interactive mode prompts for input when attaching an image

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#431]
from @km4ack:

> Trying to attach an image with pat compose from the command line:
> 
> echo "Image Attached" | pat compose km4ack -a /home/pi/Downloads/SOUTHMISSVLY_0.gif y -s "Radar"
> 
> And get the following:
> This seems to be an image. Auto resize? [Y/n]: Null message body; hope that's ok
> WARNING - Message does not validate: Empty body
> Message posted

The problem is [this block](https://github.com/la5nta/pat/blob/b9f4b0002b94402c759c8ab3243f256493bc99c5/cli_composer.go#L273-L277) which does not take into account that the caller might be a non-interactive script.

We don't prompt the user when attaching image attachments via the web gui, and we haven't received complaints about that IIRC. So removing the prompt might be a solution.

-----
Side note: `cli_composer.go` is in need of some serious cleanup. Might be a good idea to do this now.

**Comment by martinhpedersen** [comment]
@km4ack - FYI ☝️ 😊

**Comment by km4ack** [comment]
You da man!! Thanks @martinhpedersen
