### ISSUE TITLE
Ability to add more than one config per transport entry?

### ISSUE THREAD

**Issue by ctand** [la5nta/pat#433]
Hopefully I'm just being obtuse but there doesn't seem to be a way to configure multiple agwpe instances. It seems like this should be an easy thing to do. If there is please let me know. I have radio installations that are networked but physically separated so I cannot run them together on the same direwolf instance.

Thanks,

Chris, N6CTA

**Comment by harenber** [comment]
Hmm.. couldn't you just use the `--config` option to call your different setups?

```
      --config string      Path to config file. (default "/home/harenber/.config/pat/config.json")
```

At least that should/could work if you don't need to talk to your multiple radios at the same time.

73s

 Torsten DL1THM
