### ISSUE TITLE
hamlib connection failure after connection success. 

### ISSUE THREAD

**Issue by k6ef** [la5nta/pat#439]
Hamlib is configured and listening on the proper port. 
pat interactive run, it detects the radio/frequency
freq method:frequency fails with a Hamlib rig not loaded..

in ~ ➜ pat interactive                                                                                                                                 at 12:03:02 PM
2024/01/03 12:03:03 Kenwood ready. Dial frequency is 144.910.00 MHz.
> freq
Need freq method.
2024/01/03 12:03:08 Hamlib rig not loaded.

**Comment by martinhpedersen** [comment]
Hi,

Thanks for reporting this!

There is a bug in the error handling here, so you get a misleading error message.

The correct syntax is `freq <transport>`. E.g. to get the current dial frequency of the rig configured with ARDOP: `freq ardop`.

I'll include an improvement of the error handling (and usage text) in the next release. With this fix, you'll get the following output instead:

```
in ~ ➜ pat interactive
> freq
Missing transport parameter.
Syntax: freq <transport>[:<frequency>]
```

**Comment by martinhpedersen** [comment]
(tagged as invalid as this is a syntax error, not a bug)
