### ISSUE TITLE
Mac OS Installer not compatible with 10.11+

### ISSUE THREAD

**Issue by kd8drx** [la5nta/pat#47]
The Mac OS Installer package tries to install pat to /usr/bin, which is protected by [System Integrety Protection](https://support.apple.com/en-us/HT204899) in Mac OS El Capitan and later versions - causing the installer to fail. An easy solution is to install the binary to /usr/local/bin, which is the "Apple Approved" directory for such software, and is in the default $PATH.

I'm happy to build and provide the installer - being a Mac admin, I have all the tools already. Even better, I can sign the package to prevent additional security warnings.

Thanks!

**Comment by martinhpedersen** [comment]
Thank you for reporting this! I'll change it to /usr/local/bin in the next release v0.1.5.

Any contributions are welcomed :) I've already semi-automated the process of building the .pkg through [Packages](http://s.sudre.free.fr/Software/Packages/about.html), but it would be very nice to have the package signed. I will open a new issue where we can discuss this further!
