### ISSUE TITLE
Signed Mac OS releases (.dpk)

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#48]
From @kd8drx #47:
> I'm happy to build and provide the installer - being a Mac admin, I have all the tools already. Even better, I can sign the package to prevent additional security warnings.

Having the Mac OS package signed so users don't have to work around the security system in OS X would be nice!

As mentioned in #47, I've already semi-automated the .pkg packaging using using [Packages](http://s.sudre.free.fr/Software/Packages/about.html). Have a look at [osx/pat.pkgproj](https://github.com/la5nta/pat/blob/master/osx/pat.pkgproj). I do not have much experience with .pkg-packages, don't even know if I picked the right tool for the job ;)

Could you describe how you would go about packaging Pat for Mac OS? Which tools would you use?

Regarding package signing, how could we ensure that other project members can step in and sign a release if you're not available for some reason? In other words, is it possible to have multiple people signing releases?

Thanks for your interest in contributing, this is much appreciated.

**Comment by kd8drx** [comment]
Packages is exactly the tool to use - it's full featured and does everything needed. Packages can also sign packages during its build process, assuming you have a valid signing identity. Signing packages can also be done via terminal using Apple's `productsign` utility - again, assuming you have a valid signing identity.

Anyone can sign a package, assuming they have a valid identity. Getting one of those requires being a member of Apple Developer Program, which is $99 USD a year. I happen to work for a place that has a membership, thus my having a signing identity to use.

There's no reason another person couldn't sign a package if I was unavailable - it would change the name of the organization signing the package, but that's not normally visible unless you go looking for it, and the identity changing doesn't cause any warnings or errors to appear.

More importantly, in macOS Sierra (currently in beta) signing is 100% required for installer packages.

**Comment by martinhpedersen** [comment]
OK, thanks for the detailed explanation.

If the next release of Mac OS requires signing of all packages, then this is more important than I first though.

I just released v0.1.5, but I would be very happy if you're willing to help build and sign the next releases! I'll be sure to contact you when I start planning the next release.

----

Have you tried building Pat from source? This is what I did for this release:
* go version (confirming I have the latest stable release of Go)
* cd $GOPATH/src/la5nta/pat
* git pull && git checkout releases/v1.0.5
* ./make.bash
* ./pat version (confirming the git commit sha)
* cd osx && packagesbuild pat.pkgproj
* mv Pat.pkg pat_0.1.5_darwin_amd64.pkg

I believe this could be further automated/scripted, but it's not too complicated IMHO.

**Comment by martinhpedersen** [comment]
Btw, if you prefer I can build the executables and send them to you for packaging and signing.

**Comment by kd8drx** [comment]
Nope, I can build - just need to know when :)

As to signing, looks like I’m a little wrong: macOS Sierra will still let you install unsigned packages, but it hides the option and doesn’t let you whitelist it globally: http://9to5mac.com/2016/06/15/macos-sierra-gatekeeper-changes/
On Jun 30, 2016, at 14:45, Martin Hebnes Pedersen <notifications@github.com<mailto:notifications@github.com>> wrote:


Btw, if you prefer I can build the executables and send them to you for packaging and signing.

**Comment by kd8drx** [comment]
#61 Should address this, if approved.

**Comment by martinhpedersen** [comment]
OK, so I've merged #61 and committed the modified `make.bash`.

Could you build a pkg using ./make.bash from the release/v0.2.0 branch and verify that everything is OK? If it is, then please send me the signed pkg so I can test it on my iMac and publish the new release :)

I will start building for all other platforms as soon as you have verified my changes.

**Comment by martinhpedersen** [comment]
Oh, btw: This release is going to be built with Go 1.7.0 (not 1.7.1), please build with that - thanks!

**Comment by kd8drx** [comment]
Martin,
I’m not really setup to do Go builds over here, at the moment - any chance you can handle this and just send a package for me to sign?

^WPD

**Comment by martinhpedersen** [comment]
Yes, of course! I'll send it asap :)

**Comment by martinhpedersen** [comment]
Sent.

**Comment by martinhpedersen** [comment]
Will - Did you receive the file? (ping @kd8drx)

**Comment by martinhpedersen** [comment]
Will - I managed to get the package signed for this release (v0.2.0).

I appreciate all your help and hope you can help me sign the next planned release v0.2.1 in a month's time :)
