### ISSUE TITLE
macOS Sierra support

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#54]
There are some issues regarding breaking changes of ```gettimeofday``` in macOS Sierra that may cause trouble for pre Go 1.7 compiled software. We should upgrade to Go 1.7 (scheduled to be released any day now) for our v0.2.0 release. See https://github.com/golang/go/issues/16579 for more info.

In light of the macOS Sierra gatekeeper changes (issue #48) it would also be nice to have a signed release ready **before** macOS Sierra is released.

@kd8drx: Do you have access to a Mac with macOS Sierra beta installed? It would be nice to test wether or not v0.1.5 will run on it, and also start testing with Go 1.7 compiled binaries. I can provide you with pre-compiled binaries if necessary.

**Comment by kd8drx** [comment]
I do have access, yes - toss me some binaries and I’m happy to test.
On Aug 5, 2016, at 06:10, Martin Hebnes Pedersen <notifications@github.com<mailto:notifications@github.com>> wrote:


There are some issues regarding breaking changes of gettimeofday in macOS Sierra that may cause trouble for pre Go 1.7 compiled software. We should upgrade to Go 1.7 (scheduled to be released any day now) for our v0.2.0 release. See golang/go#16579<https://github.com/golang/go/issues/16579> for more info.

In light of the macOS Sierra gatekeeper changes (issue #48<https://github.com/la5nta/pat/issues/48>) it would also be nice to have a signed release ready before macOS Sierra is released.

@kd8drx<https://github.com/kd8drx>: Do you have access to a Mac with macOS Sierra beta installed? It would be nice to test wether or not v0.1.5 will run on it, and also start testing with Go 1.7 compiled binaries. I can provide you with pre-compiled binaries if necessary.

**Comment by martinhpedersen** [comment]
Thanks! I've sent you two binaries on email, one v0.2.0 compiled with Go 1.7rc5, and one v0.1.5 (from latest released pkg).

**Comment by martinhpedersen** [comment]
The Go 1.7 (final) built binary appears to work as expected:

@kd8drx (via email):
>Initial tests look good - I’m able to connect via telnet, send/receive messages, and use the web interface.
