### ISSUE TITLE
ardop: Fix rig control

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#58]
LA4TTA have reported issues with rigcontrol for ardop, no PTT control.

**Comment by DC7IA** [comment]
I just noticed that my FT-817ND transmits, but when pat tells it to stop transmitting it does not stop. Therefore I can only use VOX for connections to gateways.

Not sure which part fails:

- pat
- rigctld


(With PACTOR PTT control does not do anything at all.)

Is this connected or should I open a new issue?

**Comment by DC7IA** [comment]
Oh, invalid. Used the wrong radio ID with rigctld. :D

Used the ID 122, which is for the FT-857, which I use most of the time.
