### ISSUE TITLE
fatal error when attempting connect via web gui over ax25

### ISSUE THREAD

**Issue by kevinhooke** [la5nta/pat#59]
I'm attempting to setup Pat with Direwolf and ax25 on a Raspberry Pi. I installed Pat 0.1.5 from the arm .deb file. I have configured a wl2k port alias in /etc/ax25/axports and have added an ax25:/// connect alias in my Pat config, per the wiki docs. I can connect with axcall using an existing port in axports, so I know I have ax25 installed/configured ok.

When I select the Connect alias in the gui, the Pat app crashes with:

2016/09/07 00:20:53 Connecting to KG6SJT-10 (ax25)…
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x76f3d774]

runtime stack:
runtime.throw(0x5d0948, 0x2a)
/opt/go/src/runtime/panic.go:547 +0x78
runtime.sigpanic()
/opt/go/src/runtime/sigpanic_unix.go:12 +0x44

goroutine 53 [syscall, locked to thread]:
runtime.cgocall(0x457ff0, 0x10c6b7e4, 0x0)
/opt/go/src/runtime/cgocall.go:123 +0x11c fp=0x10c6b7c4 sp=0x10c6b7ac
github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ax25._Cfunc_ax25_aton_entry(0x0, 0x10ed00b0, 0x0)
??:0 +0x38 fp=0x10c6b7e0 sp=0x10c6b7c4
github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ax25.(*ax25Addr).setPort(0x10ed00a0, 0x10b5a250, 0x4, 0x0, 0x0)
/home/martinhpedersen/go/src/github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ax25/ax25_linux.go:361 +0x64 fp=0x10c6b7f0 sp=0x10c6b7e0
github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ax25.DialAX25Timeout(0x10b5a250, 0x4, 0x10b5a158, 0x6, 0x10d107cd, 0x9, 0x7a358200, 0xa, 0xcb8e4, 0x0, …)
/home/martinhpedersen/go/src/github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ax25/ax25_linux.go:136 +0x16c fp=0x10c6b984 sp=0x10c6b7f0
github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ax25.Dialer.DialURL(0x7a358200, 0xa, 0x10d108d0, 0x0, 0x0, 0x0, 0x0)
/home/martinhpedersen/go/src/github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ax25/ax25.go:114 +0x278 fp=0x10c6ba8c sp=0x10c6b984
github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/ax25.(*Dialer).DialURL(0x7c39f8, 0x10d108d0, 0x0, 0x0, 0x0, 0x0)
<autogenerated>:1 +0xb8 fp=0x10c6baac sp=0x10c6ba8c
github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport.DialURL(0x10d108d0, 0x0, 0x0, 0x0, 0x0)
/home/martinhpedersen/go/src/github.com/la5nta/pat/vendor/github.com/la5nta/wl2k-go/transport/dial.go:29 +0xbc fp=0x10c6bad4 sp=0x10c6baac
main.Connect(0x10d107c5, 0x11, 0x0)
/home/martinhpedersen/go/src/github.com/la5nta/pat/connect.go:108 +0x7b4 fp=0x10c6bc5c sp=0x10c6bad4
main.ConnectHandler(0x76457918, 0x10c1b200, 0x10bf8230)
/home/martinhpedersen/go/src/github.com/la5nta/pat/http.go:357 +0x68 fp=0x10c6bca8 sp=0x10c6bc5c
net/http.HandlerFunc.ServeHTTP(0x6208b4, 0x76457918, 0x10c1b200, 0x10bf8230)
/opt/go/src/net/http/server.go:1618 +0x34 fp=0x10c6bcb8 sp=0x10c6bca8
github.com/la5nta/pat/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0x10a114a0, 0x76457918, 0x10c1b200, 0x10bf8230)
/home/martinhpedersen/go/src/github.com/la5nta/pat/vendor/github.com/gorilla/mux/mux.go:107 +0x250 fp=0x10c6bd44 sp=0x10c6bcb8
net/http.(*ServeMux).ServeHTTP(0x10a0ea80, 0x76457918, 0x10c1b200, 0x10bf8230)
/opt/go/src/net/http/server.go:1910 +0x164 fp=0x10c6bd70 sp=0x10c6bd44
net/http.serverHandler.ServeHTTP(0x10a75680, 0x76457918, 0x10c1b200, 0x10bf8230)
/opt/go/src/net/http/server.go:2081 +0x190 fp=0x10c6bda0 sp=0x10c6bd70
net/http.(*conn).serve(0x10b841c0)
/opt/go/src/net/http/server.go:1472 +0xee4 fp=0x10c6bfcc sp=0x10c6bda0
runtime.goexit()
/opt/go/src/runtime/asm_arm.s:990 +0x4 fp=0x10c6bfcc sp=0x10c6bfcc
created by net/http.(*Server).Serve
/opt/go/src/net/http/server.go:2137 +0x3bc

**Comment by martinhpedersen** [comment]
Hi - thanks for the detailed bug report.

signal 0xb indicates that this is a segfault. In particular libax25 segfaults in `ax25_aton_entry()`.

Could you give me some more information regarding distro, rpi model and libax25 version?

Also, it would be helpful if you provided your $HOME/.wl2k/config.json and the relevant line from /etc/ax25/axports. Remember to remove your `secure_login_password`.

Thanks!

**Comment by kevinhooke** [comment]
Distro is Raspbian Jessie on a Pi 3
I'm not sure what libax25 version I had yesterday when I first tried this, but I had issues trying to compile paclink-unix as well, so pulled down the latest 0.0.12-rc4 from http://www.linux-ax25.org/wiki/Main_Page and this worked with paclink successfully to send and receive. I will try ago with Pat and let you know (maybe tomorrow).
/etc/ax25/axports:
1 	KK6DCT-5	1200 	255 	2 	2m packet

config.json:
{
  "mycall": "KK6DCT",
  "secure_login_password": "removed",
  "auxiliary_addresses": [],
  "locator": "CM98dn",
  "http_addr": "localhost:8080",
  "motd": [
    "Open source Winlink client - getpat.io"
  ],
  "connect_aliases": {
    "KG6SJT-10": "ax25:///KG6SJT-10",
    "telnet": "telnet://{mycall}:CMSTelnet@server.winlink.org:8772/wl2k"
  },
  "listen": [],
  "hamlib_rigs": null,
  "ax25": {
    "port": "wl2k",
    "beacon": {
      "every": 3600,
      "message": "Winlink P2P",
      "destination": "IDENT"
    },
    "rig": ""
  },
  "serial-tnc": {
    "path": "/dev/ttyUSB0",
    "baudrate": 9600,
    "type": "Kenwood"
  },
  "winmor": {
    "addr": "localhost:8500",
    "inbound_bandwidth": 1600,
    "rig": "",
    "ptt_ctrl": false
  },
  "ardop": {
    "addr": "localhost:8515",
    "arq_bandwidth": {
      "Forced": false,
      "Max": 500
    },
    "rig": "",
    "ptt_ctrl": false,
    "beacon_interval": 0,
    "cwid_enabled": true
  },
  "telnet": {
    "listen_addr": ":8774",
    "password": ""
  },
  "gpsd_addr": "localhost:2947",
  "schedule": null,
  "version_reporting_disabled": false
}

Thanks!

**Comment by martinhpedersen** [comment]
Kevin - This may be caused by a binary incompatibility issue in libax25. The Pat binaries is built against 0.0.12-rc2.

I would suggest that you either build from source (with the `libax25` build tag) or install libax25 via apt on raspbian Jessie.

If this resolves the issues I'll have to look into statically linking libax25 in future releases, or port the relevant functionality to Go.

Please keep me posted. Thanks!

**Comment by dranch** [comment]
Hello Martin,

libax25 0.0.12-rc2 is over 7 years old!  The current release version is rc4 at http://git.linux-ax25.org/cgit/libax25.git/ is 3 years old.  The top of tree in GIT and is generally considered their current stable code so I would recommend that instead.  I've asked many times for them over the years to cut a newer official versions in a quicker cadence but it hasn't happened.  This is one of the reasons why I generally recommend the VE7FET repo instead - https://github.com/ve7fet/linuxax25.

--David

**Comment by martinhpedersen** [comment]
Hi David,

I am painfully aware that the libax25 shipped with debian (and ubuntu) are old. But we have to deal with this fact and continue to support the version most commonly installed on our users systems.

As stated above, if they've broken binary compatibility, the only viable solution would be static linking or getting rid of the dependency all together. Until then, users must install a compatible libax25 or compile Pat from source... at least, that is the current working theory.

Hopefully, Kevin will give us the information needed to determine if this bug is related to libax25 version incompatibility. Then we can continue to discuss various solutions :)

**Comment by martinhpedersen** [comment]
@kevinhooke - Did you try reverting back to libax25 0.0.12-rc2?

**Comment by kevinhooke** [comment]
Sorry I didn't reply sooner - I tried against 0.0.12-rc4 and got the same error. I haven't tried rc2 or compiling from source against 0.0.12-rc2 yet ... I'm assuming that's the best way to get this working?

**Comment by martinhpedersen** [comment]
Yes, that is my theory.

But I would like Pat to be able to work regardless, so I am tempted in looking into getting rid of libax25 as a dependency. If I remember correctly, it is only used to parse `/etc/ax25/axports` and construct the AF_AX25 addresses... so it should not be too hard implementing it in Go.

But yes -  The quick solution for you is probably to install -rc2 (via apt) or compile Pat from source (`go get -tags libax25 -v github.com/la5nta/pat` using latest Go stable).

**Comment by martinhpedersen** [comment]
If you try any of the suggested methods, please keep me posted!

**Comment by martinhpedersen** [comment]
@kevinhooke - would you mind testing a binary that I've linked statically to confirm that I have resolved the issue?
