### ISSUE TITLE
Ardop v0.6 support

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#60]
ARDOP_WIN changed it's host interface in v0.6. We need to migrate to the new interface.

The host interface spec is available at the ardop development yahoo group.

The latest ardopc release also implements this new interface.

**Comment by martinhpedersen** [comment]
I've started working on this at https://github.com/la5nta/wl2k-go/pull/44

**Comment by sp2ong** [comment]
Only one simple question, I saw that the creator of ARDOP the release of version 0.8.2 and the PAT v0.2.1 supports this version of ARDOP?

**Comment by martinhpedersen** [comment]
Waldek - Yes, it should be compatible. It is compatible with the latest announced interface spec.

I have however not been able to peform a proper test of the latest ardop release yet. If you do, please let me know :)
