### ISSUE TITLE
WebGUI Linux multiusers

### ISSUE THREAD

**Issue by sp2ong** [la5nta/pat#64]
Martin,
 I hope you are very close to produce WebGUI for multiusers under linux with login to PAT via WebGUI to linux account and setup via WebGUI account on Winlink (store secure Winlink password)
It will be good solution special for HamNET network where users can connect via 2.3/5.8 Ghz tcp/ip to local server via WebGUI. The server will be forward users emails to CMS via ARDOP/Winmor or Internet :-)

I very like GetSimple CMS http://get-simple.info/ as example how to run light CMS without database. It maybe will be usefull look on GetSimple code how to create login via Web without use SQL database to store username and password

**Comment by martinhpedersen** [comment]
Yes - support for multiple users accounts would be a very interesting feature indeed.

It would have to work cross-platform though, maybe even a simple drop-down to select MYCALL (which changes default mailbox path and password) as seen in Winlink Express.

Unfortunately, I don't think this will be a priority for v1 as it probably would require a lot of refactoring and possible breaking config-structure changes. But further discussion and/or pull requests are of course welcomed :)

Until then, you could configure a debian system with multi-user systemd that fires up Pat instances on different ports for different system accounts. Though sharing a single WINMOR TNC might be problematic.

**Comment by sp2ong** [comment]
Hi Martin,

We need add authorization to login via WebGUI. I don't know now what is best solution use local unix account password or separate in config user file.

If multiuser PAT server on Linux in this case we don't need in WebGUI have access to users select any action CONNECT because PAT server will be scan folders users with waiting emails to POST via CMS. 

In this solution we separate config SERVER and USER
We can define in separate config PAT server where is information about http port, radio ports, GPS etc and add one or more options in config server where we define how often will be sync mailbox users to send waiting email for example every 30 min and
put order priority to send waiting emails. For example;

"priority":[telnet,ardop]
it means that first time server will be try send via Telnet Internet to CMS if don't work server will be try send email via radio ports use ARDOP.

Config users will simple 
{
  "mycall": "N0CALL",
  "secure_login_password": "pssword",
  "auxiliary_addresses": [],
  "locator": "XX00XX",
}
PAT server will be use mycall and password local users to sync email with CMS

It is only idea :-) and it will be nice read other opinion.

Maybe we need fork PAT to PAT Multi-user Server solution :-) because at current PAT cross-platform
for single user on own PC computer is very good and need only small enhancement :-)

**Comment by martinhpedersen** [comment]
See the proposed solution in issue #66, which should be able to provide multi-user support also. Combined with Puppet and/or containerization, you should be able to automate the setup of one Pat instance per user.

**Comment by martinhpedersen** [comment]
Although built-in multiuser support in Pat would be nice, I'm closing the issue due to the fact that it is not a priority now and it is possible to use external applications and orchestration to implement a similar solution.

If anyone want to work on this issue, please let me know and I will re-open the issue :)
