### ISSUE TITLE
WebGUI HTTP Basic authentication login

### ISSUE THREAD

**Issue by sp2ong** [la5nta/pat#66]
It will be usefull add to WebGUI maybe simple HTTP Basic authentication or more advanced method to login via WegGUI.

**Comment by martinhpedersen** [comment]
A possible solution for this could be to set up Pat behind a reverse proxy (apache/nginx) and enabling basic auth on the proxy.

See https://groups.google.com/d/msg/pat-users/v0YISh1sO4g/hbS-De1sCwAJ.

Using this method, you could also set up a multi-user environment by having the proxy route to different Pat instances (one per user), ref issue #64.
