### ISSUE TITLE
unlisten for ax25 doesn't appear to work.

### ISSUE THREAD

**Issue by jpronans** [la5nta/pat#68]
pat version
Pat v0.2.1 (4e91910) linux/arm - go1.7.3

Raspberry Pi on Compass Linux (https://github.com/nwdigitalradio/linux)

pi@rmsgw:~/Downloads $ pat interactive
> listen ax25
2016/11/07 23:22:21 Listening for incoming traffic (ax25)...
L[ax25]> unlisten ax25
L[ax25]> unlisten
No active  listener, ignoring.
L[ax25]> quit
2016/11/07 23:22:31 Unable to close ax25 listener: bad file descriptor
pi@rmsgw:~/Downloads $

**Comment by martinhpedersen** [comment]
Hi - thanks for reporting this. I will look into it :)

-- 
73 de LA5NTA
