### ISSUE TITLE
Post version info to Winlink CMS Web Services

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#8]
RMS Express and all other mainstream clients reports the user callsign, appname and version frequently to the winlink web API.

The [feature/version_report](https://github.com/la5nta/pat/tree/feature/version_report) branch implements this feature for Pat, but I guess there may be some privacy concerns about enabling this by default.

PROS:
  - Simple way to get usage statistics for Pat, the data is publicly available through the API for retrieval.
  - Needed to get the application listed under [live winlink info](http://winlink.org/RMSChannels?qt-live_winlink_information=5#qt-live_winlink_information) @ winlink.org.

CONS:
  - The data must be sent unencrypted (the API does not support https).
  - Some users may dislike the "broadcasting" of platform/application.
  - Winlink exposes a datetime-field that leaks information on when the application was running.

The feature will be optional, but enabled by default.

Feedback please :)

**Comment by martinhpedersen** [comment]
To clarify: I'm seeking feedback on whether or not to include this feature.

**Comment by dranch** [comment]
New user as of today but it seems the information being uploaded is pretty minor. I would also argue that getting this application more visibility through the Winlink system is key for it's adoption.  I'm here as I'm interested in the ARDOP/Winmor connector support which was only previously available in BPQ32

**Comment by martinhpedersen** [comment]
dranch, thanks for joining the discussion!

I believe you make a valid point regarding getting some visibility through the Winlink system. The potential gain of uploading the data is very appealing from a developers point of view. Given the importance of user growth in this stage of the project, i believe users will benefit from this too.

I'm leaning towards merging the branch, and making sure that the future configuration UI (issue #5) prompts the user and provides info on what's being uploaded.

-----------------------

_I see you have joined the pat-users list too, welcome! I haven't gotten around to writing a wiki page for ardop and winmor setup yet. So please don't hesitate to post questions if you're having questions._
