### ISSUE TITLE
PAT HTTP

### ISSUE THREAD

**Issue by Parrotsailor** [la5nta/pat#80]
will not open in lastest version of ubuntu mate...just command hangs in terminal

**Comment by martinhpedersen** [comment]
Hi!

Could you please provide some more information?

1. A copy of the config file - `cat ~/.wl2k/config.json`
2. The input/output of your terminal, including the executed command
3. The output of `pat version`
4. The output of `uname -a`

Thanks!

**Comment by martinhpedersen** [comment]
I was unable to reproduce this issue. Please provide more information and I will reopen the issue.
