### ISSUE TITLE
Web GUI: Desktop notifications

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#85]
By using the HTML5 Notifications API we can display desktop notifications when new messages are received. This could be useful when using the auto-connect feature (schedule config option) or when listening for incoming P2P connections.

One (rather big) caveat is that the Notifications API is considered a "Powerful Feature", which will require a [secure context](https://www.w3.org/TR/secure-contexts/) in the near future for most browsers. This means that the feature will only work over HTTPS or when Pat is reachable on localhost, similar to the Geolocation API (See issue #35). Chrome is the first browser to [deprecate Notifications API](https://www.chromestatus.com/feature/5759967025954816) on insecure origins, starting with Chrome 61.

Since this feature will only be available in some contexts, we should probably add some sort of status area in the GUI indicating which features are enabled in the current context.

A wiki page describing how to work around theses limitations (run on localhost, use a SSH tunnel, reverse proxy etc) would probably be a good idea. We could also [add HTTPS support](#35), but that will most likely require using self-signed certificates... which will be a cumbersome task to manage for the users, I presume.

**Comment by martinhpedersen** [comment]
It would be great to support this feature on mobile devices, but unfortunately this requires the use of Service Workers which in turn requires HTTPS (secure origin).

There are various workarounds for the secure origin requirement, so it may be worth looking into in the future.

**Comment by cbs228** [comment]
It would be useful to have a more generalized notification system. Perhaps we should add a configuration option to run user-specified shell commands upon the receipt of new unread messages. Placeholders like `$FROM` and `$SUBJECT` could be used to construct arguments to the command.

What I would really like to do is

    cat ~/.wl2k/mailbox/ME/in/SOME_NEW_MESSAGE | sendmail me

and let my local MTA take over. I could then be notified of new mail via a mailspool client, like Thunderbird. On linux, there is also `notify-send` to pop open a libnotify message or `xdg-open` to open pat in a web browser. The possibilities are numerous.

Perhaps this is a separate issue?

**Comment by martinhpedersen** [comment]
I agree, the notification system could be more generalized. The changes I have made now is very specialized for textual desktop notifications.

Instead of generating the textual content in the backend, I think the API should expose events with more structured data. In may change that before the release, if I have the time.

But yes - let's continue this discussion in a separate issue. Please see issue #87.
