### ISSUE TITLE
Web GUI does not indicate CLI is waiting for password, if password is incorrect/not configured

### ISSUE THREAD

**Issue by kk6fut** [la5nta/pat#90]
If you attempt to Connect in the GUI and you do not have a proper password configured in ./wl2k/config.json, there is no indication a password was required or incorrect within the web GUI. (the output of pat CLI instance, pat http, shows Enter secure login password: --and will continue on if you enter the password -- but the web interface never indicates it needs a password).

**Comment by martinhpedersen** [comment]
Thanks for creating this issue, and sorry for the delayed response.

Yes, this is very unfortunate and needs to be addressed asap.
