### ISSUE TITLE
Winmor and Ardop modems on same rig

### ISSUE THREAD

**Issue by frspin** [la5nta/pat#98]
I have a Powershell proc starting Winmor, Ardop and rigctl for PAT on Windows 10
Both modems are in a different directory and have a .ini file for this use.
Ardop modem start with audio from rig and transmit without problems.
Winmor modem start without getting audio from same rig and, when transmitting, I get this error:

WINMOR TNC initialization failed: Failed to initialize TNC: Enable codec failed:

Starting Winmor TNC before or after Ardop don't change the error.
Winmor and Ardon can't share same rig, connected on same USB soundcard?
Or there is a initialization problem in PAT?

Regards
Franco Spinelli
IW2DHW

**Comment by martinhpedersen** [comment]
Hi Franco!

This is certainly possible, at least on Linux.

It seems to me that you may have the sound card settings wrong for WINMOR.

I would check the audio settings for winmor, maybe re-selecting them in the
drop-down menu. The drop-down menu had a tendency to keep old devices in
the list if they have been previously selected.

https://github.com/la5nta/pat/wiki/WINMOR-TNC#audio-devices

Good luck!

-- 
Martin

1. okt. 2017 13:57 skrev "frspin" <notifications@github.com>:

**Comment by martinhpedersen** [comment]
> WINMOR TNC initialization failed: Failed to initialize TNC: Enable codec failed

This error indicates that WINMOR was not able to open it's configured audio device. It is not a Pat issue.

**Comment by martinhpedersen** [comment]
@frspin - I'm closing this issue since it's not an issue with Pat. Feel free to continue the discussion on pat-users if you want to discuss it further :-)
